/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FirmwareUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirmwareUpdateRequest{}

// FirmwareUpdateRequest Request body for firmware update operations.
type FirmwareUpdateRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Target firmware version.
	Version *string `json:"version,omitempty"`
}

type _FirmwareUpdateRequest FirmwareUpdateRequest

// NewFirmwareUpdateRequest instantiates a new FirmwareUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirmwareUpdateRequest(siteId string) *FirmwareUpdateRequest {
	this := FirmwareUpdateRequest{}
	this.SiteId = siteId
	return &this
}

// NewFirmwareUpdateRequestWithDefaults instantiates a new FirmwareUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirmwareUpdateRequestWithDefaults() *FirmwareUpdateRequest {
	this := FirmwareUpdateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *FirmwareUpdateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *FirmwareUpdateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *FirmwareUpdateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *FirmwareUpdateRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirmwareUpdateRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *FirmwareUpdateRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *FirmwareUpdateRequest) SetVersion(v string) {
	o.Version = &v
}

func (o FirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirmwareUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *FirmwareUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirmwareUpdateRequest := _FirmwareUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFirmwareUpdateRequest)

	if err != nil {
		return err
	}

	*o = FirmwareUpdateRequest(varFirmwareUpdateRequest)

	return err
}

type NullableFirmwareUpdateRequest struct {
	value *FirmwareUpdateRequest
	isSet bool
}

func (v NullableFirmwareUpdateRequest) Get() *FirmwareUpdateRequest {
	return v.value
}

func (v *NullableFirmwareUpdateRequest) Set(val *FirmwareUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmwareUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmwareUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmwareUpdateRequest(val *FirmwareUpdateRequest) *NullableFirmwareUpdateRequest {
	return &NullableFirmwareUpdateRequest{value: val, isSet: true}
}

func (v NullableFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmwareUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
