/*
Carbide REST API

Carbide REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all Carbide Sites.

API version: 1.0.2
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchUpdateExpectedMachinesRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchUpdateExpectedMachinesRequestInner{}

// BatchUpdateExpectedMachinesRequestInner struct for BatchUpdateExpectedMachinesRequestInner
type BatchUpdateExpectedMachinesRequestInner struct {
	// ID of the Expected Machine to update (required for batch operations)
	Id string `json:"id"`
	// MAC address of the Expected Machine's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Machine's BMC
	BmcUsername *string `json:"bmcUsername,omitempty"`
	// Password for accessing the Expected Machine's BMC
	BmcPassword *string `json:"bmcPassword,omitempty"`
	// Serial number of the Expected Machine's chassis
	ChassisSerialNumber *string `json:"chassisSerialNumber,omitempty"`
	// Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)
	FallbackDPUSerialNumbers []string `json:"fallbackDPUSerialNumbers,omitempty"`
	// Optional ID of the SKU to associate with this Expected Machine
	SkuId *string `json:"skuId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Machines
	Labels map[string]string `json:"labels,omitempty"`
}

type _BatchUpdateExpectedMachinesRequestInner BatchUpdateExpectedMachinesRequestInner

// NewBatchUpdateExpectedMachinesRequestInner instantiates a new BatchUpdateExpectedMachinesRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUpdateExpectedMachinesRequestInner(id string) *BatchUpdateExpectedMachinesRequestInner {
	this := BatchUpdateExpectedMachinesRequestInner{}
	this.Id = id
	return &this
}

// NewBatchUpdateExpectedMachinesRequestInnerWithDefaults instantiates a new BatchUpdateExpectedMachinesRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUpdateExpectedMachinesRequestInnerWithDefaults() *BatchUpdateExpectedMachinesRequestInner {
	this := BatchUpdateExpectedMachinesRequestInner{}
	return &this
}

// GetId returns the Id field value
func (o *BatchUpdateExpectedMachinesRequestInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BatchUpdateExpectedMachinesRequestInner) SetId(v string) {
	o.Id = v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetBmcUsername returns the BmcUsername field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcUsername() string {
	if o == nil || IsNil(o.BmcUsername) {
		var ret string
		return ret
	}
	return *o.BmcUsername
}

// GetBmcUsernameOk returns a tuple with the BmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.BmcUsername) {
		return nil, false
	}
	return o.BmcUsername, true
}

// HasBmcUsername returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasBmcUsername() bool {
	if o != nil && !IsNil(o.BmcUsername) {
		return true
	}

	return false
}

// SetBmcUsername gets a reference to the given string and assigns it to the BmcUsername field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetBmcUsername(v string) {
	o.BmcUsername = &v
}

// GetBmcPassword returns the BmcPassword field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcPassword() string {
	if o == nil || IsNil(o.BmcPassword) {
		var ret string
		return ret
	}
	return *o.BmcPassword
}

// GetBmcPasswordOk returns a tuple with the BmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetBmcPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.BmcPassword) {
		return nil, false
	}
	return o.BmcPassword, true
}

// HasBmcPassword returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasBmcPassword() bool {
	if o != nil && !IsNil(o.BmcPassword) {
		return true
	}

	return false
}

// SetBmcPassword gets a reference to the given string and assigns it to the BmcPassword field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetBmcPassword(v string) {
	o.BmcPassword = &v
}

// GetChassisSerialNumber returns the ChassisSerialNumber field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetChassisSerialNumber() string {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		var ret string
		return ret
	}
	return *o.ChassisSerialNumber
}

// GetChassisSerialNumberOk returns a tuple with the ChassisSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetChassisSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		return nil, false
	}
	return o.ChassisSerialNumber, true
}

// HasChassisSerialNumber returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasChassisSerialNumber() bool {
	if o != nil && !IsNil(o.ChassisSerialNumber) {
		return true
	}

	return false
}

// SetChassisSerialNumber gets a reference to the given string and assigns it to the ChassisSerialNumber field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetChassisSerialNumber(v string) {
	o.ChassisSerialNumber = &v
}

// GetFallbackDPUSerialNumbers returns the FallbackDPUSerialNumbers field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetFallbackDPUSerialNumbers() []string {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		var ret []string
		return ret
	}
	return o.FallbackDPUSerialNumbers
}

// GetFallbackDPUSerialNumbersOk returns a tuple with the FallbackDPUSerialNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetFallbackDPUSerialNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		return nil, false
	}
	return o.FallbackDPUSerialNumbers, true
}

// HasFallbackDPUSerialNumbers returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasFallbackDPUSerialNumbers() bool {
	if o != nil && !IsNil(o.FallbackDPUSerialNumbers) {
		return true
	}

	return false
}

// SetFallbackDPUSerialNumbers gets a reference to the given []string and assigns it to the FallbackDPUSerialNumbers field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetFallbackDPUSerialNumbers(v []string) {
	o.FallbackDPUSerialNumbers = v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetSkuId() string {
	if o == nil || IsNil(o.SkuId) {
		var ret string
		return ret
	}
	return *o.SkuId
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetSkuIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkuId) {
		return nil, false
	}
	return o.SkuId, true
}

// HasSkuId returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasSkuId() bool {
	if o != nil && !IsNil(o.SkuId) {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given string and assigns it to the SkuId field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetSkuId(v string) {
	o.SkuId = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *BatchUpdateExpectedMachinesRequestInner) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *BatchUpdateExpectedMachinesRequestInner) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *BatchUpdateExpectedMachinesRequestInner) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o BatchUpdateExpectedMachinesRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchUpdateExpectedMachinesRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.BmcUsername) {
		toSerialize["bmcUsername"] = o.BmcUsername
	}
	if !IsNil(o.BmcPassword) {
		toSerialize["bmcPassword"] = o.BmcPassword
	}
	if !IsNil(o.ChassisSerialNumber) {
		toSerialize["chassisSerialNumber"] = o.ChassisSerialNumber
	}
	if !IsNil(o.FallbackDPUSerialNumbers) {
		toSerialize["fallbackDPUSerialNumbers"] = o.FallbackDPUSerialNumbers
	}
	if !IsNil(o.SkuId) {
		toSerialize["skuId"] = o.SkuId
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *BatchUpdateExpectedMachinesRequestInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchUpdateExpectedMachinesRequestInner := _BatchUpdateExpectedMachinesRequestInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchUpdateExpectedMachinesRequestInner)

	if err != nil {
		return err
	}

	*o = BatchUpdateExpectedMachinesRequestInner(varBatchUpdateExpectedMachinesRequestInner)

	return err
}

type NullableBatchUpdateExpectedMachinesRequestInner struct {
	value *BatchUpdateExpectedMachinesRequestInner
	isSet bool
}

func (v NullableBatchUpdateExpectedMachinesRequestInner) Get() *BatchUpdateExpectedMachinesRequestInner {
	return v.value
}

func (v *NullableBatchUpdateExpectedMachinesRequestInner) Set(val *BatchUpdateExpectedMachinesRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUpdateExpectedMachinesRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUpdateExpectedMachinesRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUpdateExpectedMachinesRequestInner(val *BatchUpdateExpectedMachinesRequestInner) *NullableBatchUpdateExpectedMachinesRequestInner {
	return &NullableBatchUpdateExpectedMachinesRequestInner{value: val, isSet: true}
}

func (v NullableBatchUpdateExpectedMachinesRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUpdateExpectedMachinesRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
