/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.4
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the UsedMachineStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsedMachineStats{}

// UsedMachineStats Machine usage counts including error and maintenance states
type UsedMachineStats struct {
	// Number of Machines currently associated with Tenant Instances
	Total *int32 `json:"total,omitempty"`
	// Number of used Machines in error state
	Error *int32 `json:"error,omitempty"`
	// Number of used Machines in maintenance state
	Maintenance *int32 `json:"maintenance,omitempty"`
}

// NewUsedMachineStats instantiates a new UsedMachineStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsedMachineStats() *UsedMachineStats {
	this := UsedMachineStats{}
	return &this
}

// NewUsedMachineStatsWithDefaults instantiates a new UsedMachineStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsedMachineStatsWithDefaults() *UsedMachineStats {
	this := UsedMachineStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *UsedMachineStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsedMachineStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *UsedMachineStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *UsedMachineStats) SetTotal(v int32) {
	o.Total = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UsedMachineStats) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsedMachineStats) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UsedMachineStats) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *UsedMachineStats) SetError(v int32) {
	o.Error = &v
}

// GetMaintenance returns the Maintenance field value if set, zero value otherwise.
func (o *UsedMachineStats) GetMaintenance() int32 {
	if o == nil || IsNil(o.Maintenance) {
		var ret int32
		return ret
	}
	return *o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsedMachineStats) GetMaintenanceOk() (*int32, bool) {
	if o == nil || IsNil(o.Maintenance) {
		return nil, false
	}
	return o.Maintenance, true
}

// HasMaintenance returns a boolean if a field has been set.
func (o *UsedMachineStats) HasMaintenance() bool {
	if o != nil && !IsNil(o.Maintenance) {
		return true
	}

	return false
}

// SetMaintenance gets a reference to the given int32 and assigns it to the Maintenance field.
func (o *UsedMachineStats) SetMaintenance(v int32) {
	o.Maintenance = &v
}

func (o UsedMachineStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsedMachineStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Maintenance) {
		toSerialize["maintenance"] = o.Maintenance
	}
	return toSerialize, nil
}

type NullableUsedMachineStats struct {
	value *UsedMachineStats
	isSet bool
}

func (v NullableUsedMachineStats) Get() *UsedMachineStats {
	return v.value
}

func (v *NullableUsedMachineStats) Set(val *UsedMachineStats) {
	v.value = val
	v.isSet = true
}

func (v NullableUsedMachineStats) IsSet() bool {
	return v.isSet
}

func (v *NullableUsedMachineStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsedMachineStats(val *UsedMachineStats) *NullableUsedMachineStats {
	return &NullableUsedMachineStats{value: val, isSet: true}
}

func (v NullableUsedMachineStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsedMachineStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
