/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SubnetCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetCreateRequest{}

// SubnetCreateRequest Request data for creating Subnet
type SubnetCreateRequest struct {
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	VpcId        string  `json:"vpcId"`
	Ipv4BlockId  *string `json:"ipv4BlockId,omitempty"`
	Ipv6BlockId  *string `json:"ipv6BlockId,omitempty"`
	PrefixLength int32   `json:"prefixLength"`
}

type _SubnetCreateRequest SubnetCreateRequest

// NewSubnetCreateRequest instantiates a new SubnetCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetCreateRequest(name string, vpcId string, prefixLength int32) *SubnetCreateRequest {
	this := SubnetCreateRequest{}
	this.Name = name
	this.VpcId = vpcId
	this.PrefixLength = prefixLength
	return &this
}

// NewSubnetCreateRequestWithDefaults instantiates a new SubnetCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetCreateRequestWithDefaults() *SubnetCreateRequest {
	this := SubnetCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SubnetCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubnetCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SubnetCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SubnetCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SubnetCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetVpcId returns the VpcId field value
func (o *SubnetCreateRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *SubnetCreateRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetIpv4BlockId returns the Ipv4BlockId field value if set, zero value otherwise.
func (o *SubnetCreateRequest) GetIpv4BlockId() string {
	if o == nil || IsNil(o.Ipv4BlockId) {
		var ret string
		return ret
	}
	return *o.Ipv4BlockId
}

// GetIpv4BlockIdOk returns a tuple with the Ipv4BlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetIpv4BlockIdOk() (*string, bool) {
	if o == nil || IsNil(o.Ipv4BlockId) {
		return nil, false
	}
	return o.Ipv4BlockId, true
}

// HasIpv4BlockId returns a boolean if a field has been set.
func (o *SubnetCreateRequest) HasIpv4BlockId() bool {
	if o != nil && !IsNil(o.Ipv4BlockId) {
		return true
	}

	return false
}

// SetIpv4BlockId gets a reference to the given string and assigns it to the Ipv4BlockId field.
func (o *SubnetCreateRequest) SetIpv4BlockId(v string) {
	o.Ipv4BlockId = &v
}

// GetIpv6BlockId returns the Ipv6BlockId field value if set, zero value otherwise.
func (o *SubnetCreateRequest) GetIpv6BlockId() string {
	if o == nil || IsNil(o.Ipv6BlockId) {
		var ret string
		return ret
	}
	return *o.Ipv6BlockId
}

// GetIpv6BlockIdOk returns a tuple with the Ipv6BlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetIpv6BlockIdOk() (*string, bool) {
	if o == nil || IsNil(o.Ipv6BlockId) {
		return nil, false
	}
	return o.Ipv6BlockId, true
}

// HasIpv6BlockId returns a boolean if a field has been set.
func (o *SubnetCreateRequest) HasIpv6BlockId() bool {
	if o != nil && !IsNil(o.Ipv6BlockId) {
		return true
	}

	return false
}

// SetIpv6BlockId gets a reference to the given string and assigns it to the Ipv6BlockId field.
func (o *SubnetCreateRequest) SetIpv6BlockId(v string) {
	o.Ipv6BlockId = &v
}

// GetPrefixLength returns the PrefixLength field value
func (o *SubnetCreateRequest) GetPrefixLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value
// and a boolean to check if the value has been set.
func (o *SubnetCreateRequest) GetPrefixLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixLength, true
}

// SetPrefixLength sets field value
func (o *SubnetCreateRequest) SetPrefixLength(v int32) {
	o.PrefixLength = v
}

func (o SubnetCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["vpcId"] = o.VpcId
	if !IsNil(o.Ipv4BlockId) {
		toSerialize["ipv4BlockId"] = o.Ipv4BlockId
	}
	if !IsNil(o.Ipv6BlockId) {
		toSerialize["ipv6BlockId"] = o.Ipv6BlockId
	}
	toSerialize["prefixLength"] = o.PrefixLength
	return toSerialize, nil
}

func (o *SubnetCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"vpcId",
		"prefixLength",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnetCreateRequest := _SubnetCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubnetCreateRequest)

	if err != nil {
		return err
	}

	*o = SubnetCreateRequest(varSubnetCreateRequest)

	return err
}

type NullableSubnetCreateRequest struct {
	value *SubnetCreateRequest
	isSet bool
}

func (v NullableSubnetCreateRequest) Get() *SubnetCreateRequest {
	return v.value
}

func (v *NullableSubnetCreateRequest) Set(val *SubnetCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetCreateRequest(val *SubnetCreateRequest) *NullableSubnetCreateRequest {
	return &NullableSubnetCreateRequest{value: val, isSet: true}
}

func (v NullableSubnetCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
