/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SshKeyUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SshKeyUpdateRequest{}

// SshKeyUpdateRequest Request data to update an SSH key
type SshKeyUpdateRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewSshKeyUpdateRequest instantiates a new SshKeyUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSshKeyUpdateRequest() *SshKeyUpdateRequest {
	this := SshKeyUpdateRequest{}
	return &this
}

// NewSshKeyUpdateRequestWithDefaults instantiates a new SshKeyUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSshKeyUpdateRequestWithDefaults() *SshKeyUpdateRequest {
	this := SshKeyUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SshKeyUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SshKeyUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SshKeyUpdateRequest) SetName(v string) {
	o.Name = &v
}

func (o SshKeyUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SshKeyUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSshKeyUpdateRequest struct {
	value *SshKeyUpdateRequest
	isSet bool
}

func (v NullableSshKeyUpdateRequest) Get() *SshKeyUpdateRequest {
	return v.value
}

func (v *NullableSshKeyUpdateRequest) Set(val *SshKeyUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSshKeyUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSshKeyUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshKeyUpdateRequest(val *SshKeyUpdateRequest) *NullableSshKeyUpdateRequest {
	return &NullableSshKeyUpdateRequest{value: val, isSet: true}
}

func (v NullableSshKeyUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshKeyUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
