/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ServiceAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccount{}

// ServiceAccount Describes Service Account status and related entities
type ServiceAccount struct {
	// Indicates whether Service Account is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// ID of the Infrastructure Provider associated with Service Account
	InfrastructureProviderId *string `json:"infrastructureProviderId,omitempty"`
	// ID of the Tenant associated with Service Account
	TenantId *string `json:"tenantId,omitempty"`
}

// NewServiceAccount instantiates a new ServiceAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccount() *ServiceAccount {
	this := ServiceAccount{}
	return &this
}

// NewServiceAccountWithDefaults instantiates a new ServiceAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountWithDefaults() *ServiceAccount {
	this := ServiceAccount{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ServiceAccount) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccount) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ServiceAccount) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ServiceAccount) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *ServiceAccount) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccount) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *ServiceAccount) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *ServiceAccount) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ServiceAccount) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccount) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ServiceAccount) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ServiceAccount) SetTenantId(v string) {
	o.TenantId = &v
}

func (o ServiceAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	return toSerialize, nil
}

type NullableServiceAccount struct {
	value *ServiceAccount
	isSet bool
}

func (v NullableServiceAccount) Get() *ServiceAccount {
	return v.value
}

func (v *NullableServiceAccount) Set(val *ServiceAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccount(val *ServiceAccount) *NullableServiceAccount {
	return &NullableServiceAccount{value: val, isSet: true}
}

func (v NullableServiceAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
