/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SiteCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteCreateRequest{}

// SiteCreateRequest Request data to create a Site
type SiteCreateRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// Hostname to reach Serial Console for the Site
	SerialConsoleHostname *string       `json:"serialConsoleHostname,omitempty"`
	Location              *SiteLocation `json:"location,omitempty"`
	Contact               *SiteContact  `json:"contact,omitempty"`
}

type _SiteCreateRequest SiteCreateRequest

// NewSiteCreateRequest instantiates a new SiteCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteCreateRequest(name string) *SiteCreateRequest {
	this := SiteCreateRequest{}
	this.Name = name
	return &this
}

// NewSiteCreateRequestWithDefaults instantiates a new SiteCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteCreateRequestWithDefaults() *SiteCreateRequest {
	this := SiteCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SiteCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SiteCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SiteCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SiteCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SiteCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SiteCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSerialConsoleHostname returns the SerialConsoleHostname field value if set, zero value otherwise.
func (o *SiteCreateRequest) GetSerialConsoleHostname() string {
	if o == nil || IsNil(o.SerialConsoleHostname) {
		var ret string
		return ret
	}
	return *o.SerialConsoleHostname
}

// GetSerialConsoleHostnameOk returns a tuple with the SerialConsoleHostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCreateRequest) GetSerialConsoleHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.SerialConsoleHostname) {
		return nil, false
	}
	return o.SerialConsoleHostname, true
}

// HasSerialConsoleHostname returns a boolean if a field has been set.
func (o *SiteCreateRequest) HasSerialConsoleHostname() bool {
	if o != nil && !IsNil(o.SerialConsoleHostname) {
		return true
	}

	return false
}

// SetSerialConsoleHostname gets a reference to the given string and assigns it to the SerialConsoleHostname field.
func (o *SiteCreateRequest) SetSerialConsoleHostname(v string) {
	o.SerialConsoleHostname = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *SiteCreateRequest) GetLocation() SiteLocation {
	if o == nil || IsNil(o.Location) {
		var ret SiteLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCreateRequest) GetLocationOk() (*SiteLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *SiteCreateRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given SiteLocation and assigns it to the Location field.
func (o *SiteCreateRequest) SetLocation(v SiteLocation) {
	o.Location = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *SiteCreateRequest) GetContact() SiteContact {
	if o == nil || IsNil(o.Contact) {
		var ret SiteContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCreateRequest) GetContactOk() (*SiteContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *SiteCreateRequest) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given SiteContact and assigns it to the Contact field.
func (o *SiteCreateRequest) SetContact(v SiteContact) {
	o.Contact = &v
}

func (o SiteCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.SerialConsoleHostname) {
		toSerialize["serialConsoleHostname"] = o.SerialConsoleHostname
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	return toSerialize, nil
}

func (o *SiteCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSiteCreateRequest := _SiteCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSiteCreateRequest)

	if err != nil {
		return err
	}

	*o = SiteCreateRequest(varSiteCreateRequest)

	return err
}

type NullableSiteCreateRequest struct {
	value *SiteCreateRequest
	isSet bool
}

func (v NullableSiteCreateRequest) Get() *SiteCreateRequest {
	return v.value
}

func (v *NullableSiteCreateRequest) Set(val *SiteCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteCreateRequest(val *SiteCreateRequest) *NullableSiteCreateRequest {
	return &NullableSiteCreateRequest{value: val, isSet: true}
}

func (v NullableSiteCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
