/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SshKeyGroupCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SshKeyGroupCreateRequest{}

// SshKeyGroupCreateRequest Request data to create an SSH Key Group
type SshKeyGroupCreateRequest struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	SiteIds     []string `json:"siteIds,omitempty"`
	SshKeyIds   []string `json:"sshKeyIds,omitempty"`
}

type _SshKeyGroupCreateRequest SshKeyGroupCreateRequest

// NewSshKeyGroupCreateRequest instantiates a new SshKeyGroupCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSshKeyGroupCreateRequest(name string) *SshKeyGroupCreateRequest {
	this := SshKeyGroupCreateRequest{}
	this.Name = name
	return &this
}

// NewSshKeyGroupCreateRequestWithDefaults instantiates a new SshKeyGroupCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSshKeyGroupCreateRequestWithDefaults() *SshKeyGroupCreateRequest {
	this := SshKeyGroupCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SshKeyGroupCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SshKeyGroupCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SshKeyGroupCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SshKeyGroupCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyGroupCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SshKeyGroupCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SshKeyGroupCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSiteIds returns the SiteIds field value if set, zero value otherwise.
func (o *SshKeyGroupCreateRequest) GetSiteIds() []string {
	if o == nil || IsNil(o.SiteIds) {
		var ret []string
		return ret
	}
	return o.SiteIds
}

// GetSiteIdsOk returns a tuple with the SiteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyGroupCreateRequest) GetSiteIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SiteIds) {
		return nil, false
	}
	return o.SiteIds, true
}

// HasSiteIds returns a boolean if a field has been set.
func (o *SshKeyGroupCreateRequest) HasSiteIds() bool {
	if o != nil && !IsNil(o.SiteIds) {
		return true
	}

	return false
}

// SetSiteIds gets a reference to the given []string and assigns it to the SiteIds field.
func (o *SshKeyGroupCreateRequest) SetSiteIds(v []string) {
	o.SiteIds = v
}

// GetSshKeyIds returns the SshKeyIds field value if set, zero value otherwise.
func (o *SshKeyGroupCreateRequest) GetSshKeyIds() []string {
	if o == nil || IsNil(o.SshKeyIds) {
		var ret []string
		return ret
	}
	return o.SshKeyIds
}

// GetSshKeyIdsOk returns a tuple with the SshKeyIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyGroupCreateRequest) GetSshKeyIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SshKeyIds) {
		return nil, false
	}
	return o.SshKeyIds, true
}

// HasSshKeyIds returns a boolean if a field has been set.
func (o *SshKeyGroupCreateRequest) HasSshKeyIds() bool {
	if o != nil && !IsNil(o.SshKeyIds) {
		return true
	}

	return false
}

// SetSshKeyIds gets a reference to the given []string and assigns it to the SshKeyIds field.
func (o *SshKeyGroupCreateRequest) SetSshKeyIds(v []string) {
	o.SshKeyIds = v
}

func (o SshKeyGroupCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SshKeyGroupCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.SiteIds) {
		toSerialize["siteIds"] = o.SiteIds
	}
	if !IsNil(o.SshKeyIds) {
		toSerialize["sshKeyIds"] = o.SshKeyIds
	}
	return toSerialize, nil
}

func (o *SshKeyGroupCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSshKeyGroupCreateRequest := _SshKeyGroupCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSshKeyGroupCreateRequest)

	if err != nil {
		return err
	}

	*o = SshKeyGroupCreateRequest(varSshKeyGroupCreateRequest)

	return err
}

type NullableSshKeyGroupCreateRequest struct {
	value *SshKeyGroupCreateRequest
	isSet bool
}

func (v NullableSshKeyGroupCreateRequest) Get() *SshKeyGroupCreateRequest {
	return v.value
}

func (v *NullableSshKeyGroupCreateRequest) Set(val *SshKeyGroupCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSshKeyGroupCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSshKeyGroupCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshKeyGroupCreateRequest(val *SshKeyGroupCreateRequest) *NullableSshKeyGroupCreateRequest {
	return &NullableSshKeyGroupCreateRequest{value: val, isSet: true}
}

func (v NullableSshKeyGroupCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshKeyGroupCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
