/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InstanceTypeCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceTypeCreateRequest{}

// InstanceTypeCreateRequest Request data to create an Instance Type
type InstanceTypeCreateRequest struct {
	Name                  string                                `json:"name"`
	Description           *string                               `json:"description,omitempty"`
	SiteId                string                                `json:"siteId"`
	Labels                map[string]string                     `json:"labels,omitempty"`
	ControllerMachineType *string                               `json:"controllerMachineType,omitempty"`
	MachineCapabilities   []InstanceTypeCapabilityCreateRequest `json:"machineCapabilities,omitempty"`
}

type _InstanceTypeCreateRequest InstanceTypeCreateRequest

// NewInstanceTypeCreateRequest instantiates a new InstanceTypeCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceTypeCreateRequest(name string, siteId string) *InstanceTypeCreateRequest {
	this := InstanceTypeCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewInstanceTypeCreateRequestWithDefaults instantiates a new InstanceTypeCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceTypeCreateRequestWithDefaults() *InstanceTypeCreateRequest {
	this := InstanceTypeCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *InstanceTypeCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InstanceTypeCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InstanceTypeCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InstanceTypeCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InstanceTypeCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSiteId returns the SiteId field value
func (o *InstanceTypeCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *InstanceTypeCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InstanceTypeCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InstanceTypeCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InstanceTypeCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetControllerMachineType returns the ControllerMachineType field value if set, zero value otherwise.
func (o *InstanceTypeCreateRequest) GetControllerMachineType() string {
	if o == nil || IsNil(o.ControllerMachineType) {
		var ret string
		return ret
	}
	return *o.ControllerMachineType
}

// GetControllerMachineTypeOk returns a tuple with the ControllerMachineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetControllerMachineTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerMachineType) {
		return nil, false
	}
	return o.ControllerMachineType, true
}

// HasControllerMachineType returns a boolean if a field has been set.
func (o *InstanceTypeCreateRequest) HasControllerMachineType() bool {
	if o != nil && !IsNil(o.ControllerMachineType) {
		return true
	}

	return false
}

// SetControllerMachineType gets a reference to the given string and assigns it to the ControllerMachineType field.
func (o *InstanceTypeCreateRequest) SetControllerMachineType(v string) {
	o.ControllerMachineType = &v
}

// GetMachineCapabilities returns the MachineCapabilities field value if set, zero value otherwise.
func (o *InstanceTypeCreateRequest) GetMachineCapabilities() []InstanceTypeCapabilityCreateRequest {
	if o == nil || IsNil(o.MachineCapabilities) {
		var ret []InstanceTypeCapabilityCreateRequest
		return ret
	}
	return o.MachineCapabilities
}

// GetMachineCapabilitiesOk returns a tuple with the MachineCapabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeCreateRequest) GetMachineCapabilitiesOk() ([]InstanceTypeCapabilityCreateRequest, bool) {
	if o == nil || IsNil(o.MachineCapabilities) {
		return nil, false
	}
	return o.MachineCapabilities, true
}

// HasMachineCapabilities returns a boolean if a field has been set.
func (o *InstanceTypeCreateRequest) HasMachineCapabilities() bool {
	if o != nil && !IsNil(o.MachineCapabilities) {
		return true
	}

	return false
}

// SetMachineCapabilities gets a reference to the given []InstanceTypeCapabilityCreateRequest and assigns it to the MachineCapabilities field.
func (o *InstanceTypeCreateRequest) SetMachineCapabilities(v []InstanceTypeCapabilityCreateRequest) {
	o.MachineCapabilities = v
}

func (o InstanceTypeCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceTypeCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.ControllerMachineType) {
		toSerialize["controllerMachineType"] = o.ControllerMachineType
	}
	if !IsNil(o.MachineCapabilities) {
		toSerialize["machineCapabilities"] = o.MachineCapabilities
	}
	return toSerialize, nil
}

func (o *InstanceTypeCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceTypeCreateRequest := _InstanceTypeCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceTypeCreateRequest)

	if err != nil {
		return err
	}

	*o = InstanceTypeCreateRequest(varInstanceTypeCreateRequest)

	return err
}

type NullableInstanceTypeCreateRequest struct {
	value *InstanceTypeCreateRequest
	isSet bool
}

func (v NullableInstanceTypeCreateRequest) Get() *InstanceTypeCreateRequest {
	return v.value
}

func (v *NullableInstanceTypeCreateRequest) Set(val *InstanceTypeCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceTypeCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceTypeCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceTypeCreateRequest(val *InstanceTypeCreateRequest) *NullableInstanceTypeCreateRequest {
	return &NullableInstanceTypeCreateRequest{value: val, isSet: true}
}

func (v NullableInstanceTypeCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceTypeCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
