/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NVLinkLogicalPartitionCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NVLinkLogicalPartitionCreateRequest{}

// NVLinkLogicalPartitionCreateRequest Request data to create an NVLink Logical Partition
type NVLinkLogicalPartitionCreateRequest struct {
	// Name of the NVLink Logical Partition to create
	Name string `json:"name"`
	// Optional description of the NVLink Logical Partition
	Description *string `json:"description,omitempty"`
	// ID of the Site the NVLink Logical Partition should belong to
	SiteId string `json:"siteId"`
}

type _NVLinkLogicalPartitionCreateRequest NVLinkLogicalPartitionCreateRequest

// NewNVLinkLogicalPartitionCreateRequest instantiates a new NVLinkLogicalPartitionCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNVLinkLogicalPartitionCreateRequest(name string, siteId string) *NVLinkLogicalPartitionCreateRequest {
	this := NVLinkLogicalPartitionCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewNVLinkLogicalPartitionCreateRequestWithDefaults instantiates a new NVLinkLogicalPartitionCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNVLinkLogicalPartitionCreateRequestWithDefaults() *NVLinkLogicalPartitionCreateRequest {
	this := NVLinkLogicalPartitionCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *NVLinkLogicalPartitionCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NVLinkLogicalPartitionCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NVLinkLogicalPartitionCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NVLinkLogicalPartitionCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NVLinkLogicalPartitionCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NVLinkLogicalPartitionCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NVLinkLogicalPartitionCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSiteId returns the SiteId field value
func (o *NVLinkLogicalPartitionCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *NVLinkLogicalPartitionCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *NVLinkLogicalPartitionCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

func (o NVLinkLogicalPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NVLinkLogicalPartitionCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *NVLinkLogicalPartitionCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNVLinkLogicalPartitionCreateRequest := _NVLinkLogicalPartitionCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNVLinkLogicalPartitionCreateRequest)

	if err != nil {
		return err
	}

	*o = NVLinkLogicalPartitionCreateRequest(varNVLinkLogicalPartitionCreateRequest)

	return err
}

type NullableNVLinkLogicalPartitionCreateRequest struct {
	value *NVLinkLogicalPartitionCreateRequest
	isSet bool
}

func (v NullableNVLinkLogicalPartitionCreateRequest) Get() *NVLinkLogicalPartitionCreateRequest {
	return v.value
}

func (v *NullableNVLinkLogicalPartitionCreateRequest) Set(val *NVLinkLogicalPartitionCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNVLinkLogicalPartitionCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNVLinkLogicalPartitionCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNVLinkLogicalPartitionCreateRequest(val *NVLinkLogicalPartitionCreateRequest) *NullableNVLinkLogicalPartitionCreateRequest {
	return &NullableNVLinkLogicalPartitionCreateRequest{value: val, isSet: true}
}

func (v NullableNVLinkLogicalPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNVLinkLogicalPartitionCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
