/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the InstanceTypeUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceTypeUpdateRequest{}

// InstanceTypeUpdateRequest Request data to update an Instance Type
type InstanceTypeUpdateRequest struct {
	Name                *string             `json:"name,omitempty"`
	Description         *string             `json:"description,omitempty"`
	Labels              map[string]string   `json:"labels,omitempty"`
	MachineCapabilities []MachineCapability `json:"machineCapabilities,omitempty"`
}

// NewInstanceTypeUpdateRequest instantiates a new InstanceTypeUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceTypeUpdateRequest() *InstanceTypeUpdateRequest {
	this := InstanceTypeUpdateRequest{}
	return &this
}

// NewInstanceTypeUpdateRequestWithDefaults instantiates a new InstanceTypeUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceTypeUpdateRequestWithDefaults() *InstanceTypeUpdateRequest {
	this := InstanceTypeUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceTypeUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InstanceTypeUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceTypeUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InstanceTypeUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InstanceTypeUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InstanceTypeUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InstanceTypeUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InstanceTypeUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InstanceTypeUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetMachineCapabilities returns the MachineCapabilities field value if set, zero value otherwise.
func (o *InstanceTypeUpdateRequest) GetMachineCapabilities() []MachineCapability {
	if o == nil || IsNil(o.MachineCapabilities) {
		var ret []MachineCapability
		return ret
	}
	return o.MachineCapabilities
}

// GetMachineCapabilitiesOk returns a tuple with the MachineCapabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeUpdateRequest) GetMachineCapabilitiesOk() ([]MachineCapability, bool) {
	if o == nil || IsNil(o.MachineCapabilities) {
		return nil, false
	}
	return o.MachineCapabilities, true
}

// HasMachineCapabilities returns a boolean if a field has been set.
func (o *InstanceTypeUpdateRequest) HasMachineCapabilities() bool {
	if o != nil && !IsNil(o.MachineCapabilities) {
		return true
	}

	return false
}

// SetMachineCapabilities gets a reference to the given []MachineCapability and assigns it to the MachineCapabilities field.
func (o *InstanceTypeUpdateRequest) SetMachineCapabilities(v []MachineCapability) {
	o.MachineCapabilities = v
}

func (o InstanceTypeUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceTypeUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.MachineCapabilities) {
		toSerialize["machineCapabilities"] = o.MachineCapabilities
	}
	return toSerialize, nil
}

type NullableInstanceTypeUpdateRequest struct {
	value *InstanceTypeUpdateRequest
	isSet bool
}

func (v NullableInstanceTypeUpdateRequest) Get() *InstanceTypeUpdateRequest {
	return v.value
}

func (v *NullableInstanceTypeUpdateRequest) Set(val *InstanceTypeUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceTypeUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceTypeUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceTypeUpdateRequest(val *InstanceTypeUpdateRequest) *NullableInstanceTypeUpdateRequest {
	return &NullableInstanceTypeUpdateRequest{value: val, isSet: true}
}

func (v NullableInstanceTypeUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceTypeUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
