/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the InstanceType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceType{}

// InstanceType Instance types describe a set of machines that match a certain criteria
type InstanceType struct {
	Id                       *string             `json:"id,omitempty"`
	Name                     *string             `json:"name,omitempty"`
	Description              *string             `json:"description,omitempty"`
	ControllerMachineType    *string             `json:"controllerMachineType,omitempty"`
	InfrastructureProviderId *string             `json:"infrastructureProviderId,omitempty"`
	SiteId                   *string             `json:"siteId,omitempty"`
	Labels                   map[string]string   `json:"labels,omitempty"`
	MachineCapabilities      []MachineCapability `json:"machineCapabilities,omitempty"`
	// Available only for Providers
	MachineInstanceTypes []MachineInstanceType `json:"machineInstanceTypes,omitempty"`
	// summary of machine counts by allocation status
	AllocationStats *InstanceTypeAllocationStats `json:"allocationStats,omitempty"`
	Status          *InstanceTypeStatus          `json:"status,omitempty"`
	StatusHistory   []StatusDetail               `json:"statusHistory,omitempty"`
	Deprecations    []Deprecation                `json:"deprecations,omitempty"`
	Created         *time.Time                   `json:"created,omitempty"`
	Updated         *time.Time                   `json:"updated,omitempty"`
}

// NewInstanceType instantiates a new InstanceType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceType() *InstanceType {
	this := InstanceType{}
	return &this
}

// NewInstanceTypeWithDefaults instantiates a new InstanceType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceTypeWithDefaults() *InstanceType {
	this := InstanceType{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstanceType) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InstanceType) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InstanceType) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceType) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InstanceType) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceType) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InstanceType) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InstanceType) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InstanceType) SetDescription(v string) {
	o.Description = &v
}

// GetControllerMachineType returns the ControllerMachineType field value if set, zero value otherwise.
func (o *InstanceType) GetControllerMachineType() string {
	if o == nil || IsNil(o.ControllerMachineType) {
		var ret string
		return ret
	}
	return *o.ControllerMachineType
}

// GetControllerMachineTypeOk returns a tuple with the ControllerMachineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetControllerMachineTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerMachineType) {
		return nil, false
	}
	return o.ControllerMachineType, true
}

// HasControllerMachineType returns a boolean if a field has been set.
func (o *InstanceType) HasControllerMachineType() bool {
	if o != nil && !IsNil(o.ControllerMachineType) {
		return true
	}

	return false
}

// SetControllerMachineType gets a reference to the given string and assigns it to the ControllerMachineType field.
func (o *InstanceType) SetControllerMachineType(v string) {
	o.ControllerMachineType = &v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *InstanceType) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *InstanceType) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *InstanceType) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *InstanceType) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *InstanceType) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *InstanceType) SetSiteId(v string) {
	o.SiteId = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InstanceType) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InstanceType) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InstanceType) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetMachineCapabilities returns the MachineCapabilities field value if set, zero value otherwise.
func (o *InstanceType) GetMachineCapabilities() []MachineCapability {
	if o == nil || IsNil(o.MachineCapabilities) {
		var ret []MachineCapability
		return ret
	}
	return o.MachineCapabilities
}

// GetMachineCapabilitiesOk returns a tuple with the MachineCapabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetMachineCapabilitiesOk() ([]MachineCapability, bool) {
	if o == nil || IsNil(o.MachineCapabilities) {
		return nil, false
	}
	return o.MachineCapabilities, true
}

// HasMachineCapabilities returns a boolean if a field has been set.
func (o *InstanceType) HasMachineCapabilities() bool {
	if o != nil && !IsNil(o.MachineCapabilities) {
		return true
	}

	return false
}

// SetMachineCapabilities gets a reference to the given []MachineCapability and assigns it to the MachineCapabilities field.
func (o *InstanceType) SetMachineCapabilities(v []MachineCapability) {
	o.MachineCapabilities = v
}

// GetMachineInstanceTypes returns the MachineInstanceTypes field value if set, zero value otherwise.
func (o *InstanceType) GetMachineInstanceTypes() []MachineInstanceType {
	if o == nil || IsNil(o.MachineInstanceTypes) {
		var ret []MachineInstanceType
		return ret
	}
	return o.MachineInstanceTypes
}

// GetMachineInstanceTypesOk returns a tuple with the MachineInstanceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetMachineInstanceTypesOk() ([]MachineInstanceType, bool) {
	if o == nil || IsNil(o.MachineInstanceTypes) {
		return nil, false
	}
	return o.MachineInstanceTypes, true
}

// HasMachineInstanceTypes returns a boolean if a field has been set.
func (o *InstanceType) HasMachineInstanceTypes() bool {
	if o != nil && !IsNil(o.MachineInstanceTypes) {
		return true
	}

	return false
}

// SetMachineInstanceTypes gets a reference to the given []MachineInstanceType and assigns it to the MachineInstanceTypes field.
func (o *InstanceType) SetMachineInstanceTypes(v []MachineInstanceType) {
	o.MachineInstanceTypes = v
}

// GetAllocationStats returns the AllocationStats field value if set, zero value otherwise.
func (o *InstanceType) GetAllocationStats() InstanceTypeAllocationStats {
	if o == nil || IsNil(o.AllocationStats) {
		var ret InstanceTypeAllocationStats
		return ret
	}
	return *o.AllocationStats
}

// GetAllocationStatsOk returns a tuple with the AllocationStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetAllocationStatsOk() (*InstanceTypeAllocationStats, bool) {
	if o == nil || IsNil(o.AllocationStats) {
		return nil, false
	}
	return o.AllocationStats, true
}

// HasAllocationStats returns a boolean if a field has been set.
func (o *InstanceType) HasAllocationStats() bool {
	if o != nil && !IsNil(o.AllocationStats) {
		return true
	}

	return false
}

// SetAllocationStats gets a reference to the given InstanceTypeAllocationStats and assigns it to the AllocationStats field.
func (o *InstanceType) SetAllocationStats(v InstanceTypeAllocationStats) {
	o.AllocationStats = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InstanceType) GetStatus() InstanceTypeStatus {
	if o == nil || IsNil(o.Status) {
		var ret InstanceTypeStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetStatusOk() (*InstanceTypeStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InstanceType) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InstanceTypeStatus and assigns it to the Status field.
func (o *InstanceType) SetStatus(v InstanceTypeStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *InstanceType) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *InstanceType) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *InstanceType) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetDeprecations returns the Deprecations field value if set, zero value otherwise.
func (o *InstanceType) GetDeprecations() []Deprecation {
	if o == nil || IsNil(o.Deprecations) {
		var ret []Deprecation
		return ret
	}
	return o.Deprecations
}

// GetDeprecationsOk returns a tuple with the Deprecations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetDeprecationsOk() ([]Deprecation, bool) {
	if o == nil || IsNil(o.Deprecations) {
		return nil, false
	}
	return o.Deprecations, true
}

// HasDeprecations returns a boolean if a field has been set.
func (o *InstanceType) HasDeprecations() bool {
	if o != nil && !IsNil(o.Deprecations) {
		return true
	}

	return false
}

// SetDeprecations gets a reference to the given []Deprecation and assigns it to the Deprecations field.
func (o *InstanceType) SetDeprecations(v []Deprecation) {
	o.Deprecations = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *InstanceType) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *InstanceType) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *InstanceType) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *InstanceType) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceType) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *InstanceType) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *InstanceType) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o InstanceType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ControllerMachineType) {
		toSerialize["controllerMachineType"] = o.ControllerMachineType
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.MachineCapabilities) {
		toSerialize["machineCapabilities"] = o.MachineCapabilities
	}
	if !IsNil(o.MachineInstanceTypes) {
		toSerialize["machineInstanceTypes"] = o.MachineInstanceTypes
	}
	if !IsNil(o.AllocationStats) {
		toSerialize["allocationStats"] = o.AllocationStats
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Deprecations) {
		toSerialize["deprecations"] = o.Deprecations
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableInstanceType struct {
	value *InstanceType
	isSet bool
}

func (v NullableInstanceType) Get() *InstanceType {
	return v.value
}

func (v *NullableInstanceType) Set(val *InstanceType) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceType) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceType(val *InstanceType) *NullableInstanceType {
	return &NullableInstanceType{value: val, isSet: true}
}

func (v NullableInstanceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
