/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteUpdateRequest{}

// SiteUpdateRequest Request data to update a Site
type SiteUpdateRequest struct {
	// Update name of the Site. Can only be updated by Provider
	Name *string `json:"name,omitempty"`
	// Update description for the Site. Can only be updated by Provider
	Description *string `json:"description,omitempty"`
	// Set to true to issue a new registration token. Can only be updated by Provider
	RenewRegistrationToken *bool `json:"renewRegistrationToken,omitempty"`
	// Hostname to reach Serial Console for the Site. Can only be updated by Provider
	SerialConsoleHostname *string `json:"serialConsoleHostname,omitempty"`
	// Enable/disable Serial Console. Can only be updated by Provider
	IsSerialConsoleEnabled *bool `json:"isSerialConsoleEnabled,omitempty"`
	// Maximum idle time in seconds before Serial Console is disconnected. Can only be updated by Provider
	SerialConsoleIdleTimeout *int32 `json:"serialConsoleIdleTimeout,omitempty"`
	// Maximum length of Serial Console session in seconds. Can only be updated by Provider
	SerialConsoleMaxSessionLength *int32 `json:"serialConsoleMaxSessionLength,omitempty"`
	// Enable/disable Serial Console access using SSH Keys. Can only be updated by Tenant
	IsSerialConsoleSSHKeysEnabled *bool         `json:"isSerialConsoleSSHKeysEnabled,omitempty"`
	Location                      *SiteLocation `json:"location,omitempty"`
	Contact                       *SiteContact  `json:"contact,omitempty"`
}

// NewSiteUpdateRequest instantiates a new SiteUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteUpdateRequest() *SiteUpdateRequest {
	this := SiteUpdateRequest{}
	return &this
}

// NewSiteUpdateRequestWithDefaults instantiates a new SiteUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteUpdateRequestWithDefaults() *SiteUpdateRequest {
	this := SiteUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SiteUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SiteUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRenewRegistrationToken returns the RenewRegistrationToken field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetRenewRegistrationToken() bool {
	if o == nil || IsNil(o.RenewRegistrationToken) {
		var ret bool
		return ret
	}
	return *o.RenewRegistrationToken
}

// GetRenewRegistrationTokenOk returns a tuple with the RenewRegistrationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetRenewRegistrationTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.RenewRegistrationToken) {
		return nil, false
	}
	return o.RenewRegistrationToken, true
}

// HasRenewRegistrationToken returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasRenewRegistrationToken() bool {
	if o != nil && !IsNil(o.RenewRegistrationToken) {
		return true
	}

	return false
}

// SetRenewRegistrationToken gets a reference to the given bool and assigns it to the RenewRegistrationToken field.
func (o *SiteUpdateRequest) SetRenewRegistrationToken(v bool) {
	o.RenewRegistrationToken = &v
}

// GetSerialConsoleHostname returns the SerialConsoleHostname field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetSerialConsoleHostname() string {
	if o == nil || IsNil(o.SerialConsoleHostname) {
		var ret string
		return ret
	}
	return *o.SerialConsoleHostname
}

// GetSerialConsoleHostnameOk returns a tuple with the SerialConsoleHostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetSerialConsoleHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.SerialConsoleHostname) {
		return nil, false
	}
	return o.SerialConsoleHostname, true
}

// HasSerialConsoleHostname returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasSerialConsoleHostname() bool {
	if o != nil && !IsNil(o.SerialConsoleHostname) {
		return true
	}

	return false
}

// SetSerialConsoleHostname gets a reference to the given string and assigns it to the SerialConsoleHostname field.
func (o *SiteUpdateRequest) SetSerialConsoleHostname(v string) {
	o.SerialConsoleHostname = &v
}

// GetIsSerialConsoleEnabled returns the IsSerialConsoleEnabled field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetIsSerialConsoleEnabled() bool {
	if o == nil || IsNil(o.IsSerialConsoleEnabled) {
		var ret bool
		return ret
	}
	return *o.IsSerialConsoleEnabled
}

// GetIsSerialConsoleEnabledOk returns a tuple with the IsSerialConsoleEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetIsSerialConsoleEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSerialConsoleEnabled) {
		return nil, false
	}
	return o.IsSerialConsoleEnabled, true
}

// HasIsSerialConsoleEnabled returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasIsSerialConsoleEnabled() bool {
	if o != nil && !IsNil(o.IsSerialConsoleEnabled) {
		return true
	}

	return false
}

// SetIsSerialConsoleEnabled gets a reference to the given bool and assigns it to the IsSerialConsoleEnabled field.
func (o *SiteUpdateRequest) SetIsSerialConsoleEnabled(v bool) {
	o.IsSerialConsoleEnabled = &v
}

// GetSerialConsoleIdleTimeout returns the SerialConsoleIdleTimeout field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetSerialConsoleIdleTimeout() int32 {
	if o == nil || IsNil(o.SerialConsoleIdleTimeout) {
		var ret int32
		return ret
	}
	return *o.SerialConsoleIdleTimeout
}

// GetSerialConsoleIdleTimeoutOk returns a tuple with the SerialConsoleIdleTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetSerialConsoleIdleTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.SerialConsoleIdleTimeout) {
		return nil, false
	}
	return o.SerialConsoleIdleTimeout, true
}

// HasSerialConsoleIdleTimeout returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasSerialConsoleIdleTimeout() bool {
	if o != nil && !IsNil(o.SerialConsoleIdleTimeout) {
		return true
	}

	return false
}

// SetSerialConsoleIdleTimeout gets a reference to the given int32 and assigns it to the SerialConsoleIdleTimeout field.
func (o *SiteUpdateRequest) SetSerialConsoleIdleTimeout(v int32) {
	o.SerialConsoleIdleTimeout = &v
}

// GetSerialConsoleMaxSessionLength returns the SerialConsoleMaxSessionLength field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetSerialConsoleMaxSessionLength() int32 {
	if o == nil || IsNil(o.SerialConsoleMaxSessionLength) {
		var ret int32
		return ret
	}
	return *o.SerialConsoleMaxSessionLength
}

// GetSerialConsoleMaxSessionLengthOk returns a tuple with the SerialConsoleMaxSessionLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetSerialConsoleMaxSessionLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.SerialConsoleMaxSessionLength) {
		return nil, false
	}
	return o.SerialConsoleMaxSessionLength, true
}

// HasSerialConsoleMaxSessionLength returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasSerialConsoleMaxSessionLength() bool {
	if o != nil && !IsNil(o.SerialConsoleMaxSessionLength) {
		return true
	}

	return false
}

// SetSerialConsoleMaxSessionLength gets a reference to the given int32 and assigns it to the SerialConsoleMaxSessionLength field.
func (o *SiteUpdateRequest) SetSerialConsoleMaxSessionLength(v int32) {
	o.SerialConsoleMaxSessionLength = &v
}

// GetIsSerialConsoleSSHKeysEnabled returns the IsSerialConsoleSSHKeysEnabled field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetIsSerialConsoleSSHKeysEnabled() bool {
	if o == nil || IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		var ret bool
		return ret
	}
	return *o.IsSerialConsoleSSHKeysEnabled
}

// GetIsSerialConsoleSSHKeysEnabledOk returns a tuple with the IsSerialConsoleSSHKeysEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetIsSerialConsoleSSHKeysEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		return nil, false
	}
	return o.IsSerialConsoleSSHKeysEnabled, true
}

// HasIsSerialConsoleSSHKeysEnabled returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasIsSerialConsoleSSHKeysEnabled() bool {
	if o != nil && !IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		return true
	}

	return false
}

// SetIsSerialConsoleSSHKeysEnabled gets a reference to the given bool and assigns it to the IsSerialConsoleSSHKeysEnabled field.
func (o *SiteUpdateRequest) SetIsSerialConsoleSSHKeysEnabled(v bool) {
	o.IsSerialConsoleSSHKeysEnabled = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetLocation() SiteLocation {
	if o == nil || IsNil(o.Location) {
		var ret SiteLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetLocationOk() (*SiteLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given SiteLocation and assigns it to the Location field.
func (o *SiteUpdateRequest) SetLocation(v SiteLocation) {
	o.Location = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *SiteUpdateRequest) GetContact() SiteContact {
	if o == nil || IsNil(o.Contact) {
		var ret SiteContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteUpdateRequest) GetContactOk() (*SiteContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *SiteUpdateRequest) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given SiteContact and assigns it to the Contact field.
func (o *SiteUpdateRequest) SetContact(v SiteContact) {
	o.Contact = &v
}

func (o SiteUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RenewRegistrationToken) {
		toSerialize["renewRegistrationToken"] = o.RenewRegistrationToken
	}
	if !IsNil(o.SerialConsoleHostname) {
		toSerialize["serialConsoleHostname"] = o.SerialConsoleHostname
	}
	if !IsNil(o.IsSerialConsoleEnabled) {
		toSerialize["isSerialConsoleEnabled"] = o.IsSerialConsoleEnabled
	}
	if !IsNil(o.SerialConsoleIdleTimeout) {
		toSerialize["serialConsoleIdleTimeout"] = o.SerialConsoleIdleTimeout
	}
	if !IsNil(o.SerialConsoleMaxSessionLength) {
		toSerialize["serialConsoleMaxSessionLength"] = o.SerialConsoleMaxSessionLength
	}
	if !IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		toSerialize["isSerialConsoleSSHKeysEnabled"] = o.IsSerialConsoleSSHKeysEnabled
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	return toSerialize, nil
}

type NullableSiteUpdateRequest struct {
	value *SiteUpdateRequest
	isSet bool
}

func (v NullableSiteUpdateRequest) Get() *SiteUpdateRequest {
	return v.value
}

func (v *NullableSiteUpdateRequest) Set(val *SiteUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteUpdateRequest(val *SiteUpdateRequest) *NullableSiteUpdateRequest {
	return &NullableSiteUpdateRequest{value: val, isSet: true}
}

func (v NullableSiteUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
