/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the IpBlockUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpBlockUpdateRequest{}

// IpBlockUpdateRequest Request data for editing IP block
type IpBlockUpdateRequest struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewIpBlockUpdateRequest instantiates a new IpBlockUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpBlockUpdateRequest() *IpBlockUpdateRequest {
	this := IpBlockUpdateRequest{}
	return &this
}

// NewIpBlockUpdateRequestWithDefaults instantiates a new IpBlockUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpBlockUpdateRequestWithDefaults() *IpBlockUpdateRequest {
	this := IpBlockUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IpBlockUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IpBlockUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IpBlockUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IpBlockUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IpBlockUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IpBlockUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

func (o IpBlockUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpBlockUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableIpBlockUpdateRequest struct {
	value *IpBlockUpdateRequest
	isSet bool
}

func (v NullableIpBlockUpdateRequest) Get() *IpBlockUpdateRequest {
	return v.value
}

func (v *NullableIpBlockUpdateRequest) Set(val *IpBlockUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIpBlockUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIpBlockUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpBlockUpdateRequest(val *IpBlockUpdateRequest) *NullableIpBlockUpdateRequest {
	return &NullableIpBlockUpdateRequest{value: val, isSet: true}
}

func (v NullableIpBlockUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpBlockUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
