/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineGPUInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineGPUInfo{}

// MachineGPUInfo Describes information about GPU of a Machine
type MachineGPUInfo struct {
	Name           *string `json:"name,omitempty"`
	Serial         *string `json:"serial,omitempty"`
	DriverVersion  *string `json:"driverVersion,omitempty"`
	VbiosVersion   *string `json:"vbiosVersion,omitempty"`
	InforomVersion *string `json:"inforomVersion,omitempty"`
	TotalMemory    *string `json:"totalMemory,omitempty"`
	Frequency      *string `json:"frequency,omitempty"`
	PciBusId       *string `json:"pciBusId,omitempty"`
}

// NewMachineGPUInfo instantiates a new MachineGPUInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineGPUInfo() *MachineGPUInfo {
	this := MachineGPUInfo{}
	return &this
}

// NewMachineGPUInfoWithDefaults instantiates a new MachineGPUInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineGPUInfoWithDefaults() *MachineGPUInfo {
	this := MachineGPUInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MachineGPUInfo) SetName(v string) {
	o.Name = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *MachineGPUInfo) SetSerial(v string) {
	o.Serial = &v
}

// GetDriverVersion returns the DriverVersion field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetDriverVersion() string {
	if o == nil || IsNil(o.DriverVersion) {
		var ret string
		return ret
	}
	return *o.DriverVersion
}

// GetDriverVersionOk returns a tuple with the DriverVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetDriverVersionOk() (*string, bool) {
	if o == nil || IsNil(o.DriverVersion) {
		return nil, false
	}
	return o.DriverVersion, true
}

// HasDriverVersion returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasDriverVersion() bool {
	if o != nil && !IsNil(o.DriverVersion) {
		return true
	}

	return false
}

// SetDriverVersion gets a reference to the given string and assigns it to the DriverVersion field.
func (o *MachineGPUInfo) SetDriverVersion(v string) {
	o.DriverVersion = &v
}

// GetVbiosVersion returns the VbiosVersion field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetVbiosVersion() string {
	if o == nil || IsNil(o.VbiosVersion) {
		var ret string
		return ret
	}
	return *o.VbiosVersion
}

// GetVbiosVersionOk returns a tuple with the VbiosVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetVbiosVersionOk() (*string, bool) {
	if o == nil || IsNil(o.VbiosVersion) {
		return nil, false
	}
	return o.VbiosVersion, true
}

// HasVbiosVersion returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasVbiosVersion() bool {
	if o != nil && !IsNil(o.VbiosVersion) {
		return true
	}

	return false
}

// SetVbiosVersion gets a reference to the given string and assigns it to the VbiosVersion field.
func (o *MachineGPUInfo) SetVbiosVersion(v string) {
	o.VbiosVersion = &v
}

// GetInforomVersion returns the InforomVersion field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetInforomVersion() string {
	if o == nil || IsNil(o.InforomVersion) {
		var ret string
		return ret
	}
	return *o.InforomVersion
}

// GetInforomVersionOk returns a tuple with the InforomVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetInforomVersionOk() (*string, bool) {
	if o == nil || IsNil(o.InforomVersion) {
		return nil, false
	}
	return o.InforomVersion, true
}

// HasInforomVersion returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasInforomVersion() bool {
	if o != nil && !IsNil(o.InforomVersion) {
		return true
	}

	return false
}

// SetInforomVersion gets a reference to the given string and assigns it to the InforomVersion field.
func (o *MachineGPUInfo) SetInforomVersion(v string) {
	o.InforomVersion = &v
}

// GetTotalMemory returns the TotalMemory field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetTotalMemory() string {
	if o == nil || IsNil(o.TotalMemory) {
		var ret string
		return ret
	}
	return *o.TotalMemory
}

// GetTotalMemoryOk returns a tuple with the TotalMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetTotalMemoryOk() (*string, bool) {
	if o == nil || IsNil(o.TotalMemory) {
		return nil, false
	}
	return o.TotalMemory, true
}

// HasTotalMemory returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasTotalMemory() bool {
	if o != nil && !IsNil(o.TotalMemory) {
		return true
	}

	return false
}

// SetTotalMemory gets a reference to the given string and assigns it to the TotalMemory field.
func (o *MachineGPUInfo) SetTotalMemory(v string) {
	o.TotalMemory = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *MachineGPUInfo) SetFrequency(v string) {
	o.Frequency = &v
}

// GetPciBusId returns the PciBusId field value if set, zero value otherwise.
func (o *MachineGPUInfo) GetPciBusId() string {
	if o == nil || IsNil(o.PciBusId) {
		var ret string
		return ret
	}
	return *o.PciBusId
}

// GetPciBusIdOk returns a tuple with the PciBusId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineGPUInfo) GetPciBusIdOk() (*string, bool) {
	if o == nil || IsNil(o.PciBusId) {
		return nil, false
	}
	return o.PciBusId, true
}

// HasPciBusId returns a boolean if a field has been set.
func (o *MachineGPUInfo) HasPciBusId() bool {
	if o != nil && !IsNil(o.PciBusId) {
		return true
	}

	return false
}

// SetPciBusId gets a reference to the given string and assigns it to the PciBusId field.
func (o *MachineGPUInfo) SetPciBusId(v string) {
	o.PciBusId = &v
}

func (o MachineGPUInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineGPUInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if !IsNil(o.DriverVersion) {
		toSerialize["driverVersion"] = o.DriverVersion
	}
	if !IsNil(o.VbiosVersion) {
		toSerialize["vbiosVersion"] = o.VbiosVersion
	}
	if !IsNil(o.InforomVersion) {
		toSerialize["inforomVersion"] = o.InforomVersion
	}
	if !IsNil(o.TotalMemory) {
		toSerialize["totalMemory"] = o.TotalMemory
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.PciBusId) {
		toSerialize["pciBusId"] = o.PciBusId
	}
	return toSerialize, nil
}

type NullableMachineGPUInfo struct {
	value *MachineGPUInfo
	isSet bool
}

func (v NullableMachineGPUInfo) Get() *MachineGPUInfo {
	return v.value
}

func (v *NullableMachineGPUInfo) Set(val *MachineGPUInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineGPUInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineGPUInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineGPUInfo(val *MachineGPUInfo) *NullableMachineGPUInfo {
	return &NullableMachineGPUInfo{value: val, isSet: true}
}

func (v NullableMachineGPUInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineGPUInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
