/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InfiniBandPartitionUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfiniBandPartitionUpdateRequest{}

// InfiniBandPartitionUpdateRequest Request data to update an InfiniBand Partition
type InfiniBandPartitionUpdateRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type _InfiniBandPartitionUpdateRequest InfiniBandPartitionUpdateRequest

// NewInfiniBandPartitionUpdateRequest instantiates a new InfiniBandPartitionUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfiniBandPartitionUpdateRequest(name string) *InfiniBandPartitionUpdateRequest {
	this := InfiniBandPartitionUpdateRequest{}
	this.Name = name
	return &this
}

// NewInfiniBandPartitionUpdateRequestWithDefaults instantiates a new InfiniBandPartitionUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfiniBandPartitionUpdateRequestWithDefaults() *InfiniBandPartitionUpdateRequest {
	this := InfiniBandPartitionUpdateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *InfiniBandPartitionUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InfiniBandPartitionUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InfiniBandPartitionUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InfiniBandPartitionUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartitionUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InfiniBandPartitionUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InfiniBandPartitionUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

func (o InfiniBandPartitionUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfiniBandPartitionUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *InfiniBandPartitionUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInfiniBandPartitionUpdateRequest := _InfiniBandPartitionUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInfiniBandPartitionUpdateRequest)

	if err != nil {
		return err
	}

	*o = InfiniBandPartitionUpdateRequest(varInfiniBandPartitionUpdateRequest)

	return err
}

type NullableInfiniBandPartitionUpdateRequest struct {
	value *InfiniBandPartitionUpdateRequest
	isSet bool
}

func (v NullableInfiniBandPartitionUpdateRequest) Get() *InfiniBandPartitionUpdateRequest {
	return v.value
}

func (v *NullableInfiniBandPartitionUpdateRequest) Set(val *InfiniBandPartitionUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInfiniBandPartitionUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInfiniBandPartitionUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfiniBandPartitionUpdateRequest(val *InfiniBandPartitionUpdateRequest) *NullableInfiniBandPartitionUpdateRequest {
	return &NullableInfiniBandPartitionUpdateRequest{value: val, isSet: true}
}

func (v NullableInfiniBandPartitionUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfiniBandPartitionUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
