/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AllocationConstraintCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllocationConstraintCreateRequest{}

// AllocationConstraintCreateRequest Request data to create an AllocationConstraint
type AllocationConstraintCreateRequest struct {
	ResourceType    *string `json:"resourceType,omitempty"`
	ResourceTypeId  string  `json:"resourceTypeId"`
	ConstraintType  string  `json:"constraintType"`
	ConstraintValue int32   `json:"constraintValue"`
}

type _AllocationConstraintCreateRequest AllocationConstraintCreateRequest

// NewAllocationConstraintCreateRequest instantiates a new AllocationConstraintCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllocationConstraintCreateRequest(resourceTypeId string, constraintType string, constraintValue int32) *AllocationConstraintCreateRequest {
	this := AllocationConstraintCreateRequest{}
	this.ResourceTypeId = resourceTypeId
	this.ConstraintType = constraintType
	this.ConstraintValue = constraintValue
	return &this
}

// NewAllocationConstraintCreateRequestWithDefaults instantiates a new AllocationConstraintCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllocationConstraintCreateRequestWithDefaults() *AllocationConstraintCreateRequest {
	this := AllocationConstraintCreateRequest{}
	return &this
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *AllocationConstraintCreateRequest) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationConstraintCreateRequest) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *AllocationConstraintCreateRequest) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *AllocationConstraintCreateRequest) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetResourceTypeId returns the ResourceTypeId field value
func (o *AllocationConstraintCreateRequest) GetResourceTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceTypeId
}

// GetResourceTypeIdOk returns a tuple with the ResourceTypeId field value
// and a boolean to check if the value has been set.
func (o *AllocationConstraintCreateRequest) GetResourceTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceTypeId, true
}

// SetResourceTypeId sets field value
func (o *AllocationConstraintCreateRequest) SetResourceTypeId(v string) {
	o.ResourceTypeId = v
}

// GetConstraintType returns the ConstraintType field value
func (o *AllocationConstraintCreateRequest) GetConstraintType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConstraintType
}

// GetConstraintTypeOk returns a tuple with the ConstraintType field value
// and a boolean to check if the value has been set.
func (o *AllocationConstraintCreateRequest) GetConstraintTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConstraintType, true
}

// SetConstraintType sets field value
func (o *AllocationConstraintCreateRequest) SetConstraintType(v string) {
	o.ConstraintType = v
}

// GetConstraintValue returns the ConstraintValue field value
func (o *AllocationConstraintCreateRequest) GetConstraintValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConstraintValue
}

// GetConstraintValueOk returns a tuple with the ConstraintValue field value
// and a boolean to check if the value has been set.
func (o *AllocationConstraintCreateRequest) GetConstraintValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConstraintValue, true
}

// SetConstraintValue sets field value
func (o *AllocationConstraintCreateRequest) SetConstraintValue(v int32) {
	o.ConstraintValue = v
}

func (o AllocationConstraintCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllocationConstraintCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	toSerialize["resourceTypeId"] = o.ResourceTypeId
	toSerialize["constraintType"] = o.ConstraintType
	toSerialize["constraintValue"] = o.ConstraintValue
	return toSerialize, nil
}

func (o *AllocationConstraintCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resourceTypeId",
		"constraintType",
		"constraintValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAllocationConstraintCreateRequest := _AllocationConstraintCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAllocationConstraintCreateRequest)

	if err != nil {
		return err
	}

	*o = AllocationConstraintCreateRequest(varAllocationConstraintCreateRequest)

	return err
}

type NullableAllocationConstraintCreateRequest struct {
	value *AllocationConstraintCreateRequest
	isSet bool
}

func (v NullableAllocationConstraintCreateRequest) Get() *AllocationConstraintCreateRequest {
	return v.value
}

func (v *NullableAllocationConstraintCreateRequest) Set(val *AllocationConstraintCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocationConstraintCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocationConstraintCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocationConstraintCreateRequest(val *AllocationConstraintCreateRequest) *NullableAllocationConstraintCreateRequest {
	return &NullableAllocationConstraintCreateRequest{value: val, isSet: true}
}

func (v NullableAllocationConstraintCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocationConstraintCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
