/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineInfiniBandInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineInfiniBandInterface{}

// MachineInfiniBandInterface Describes information about an Infiniband Interface of a Machine
type MachineInfiniBandInterface struct {
	Guid        *string `json:"guid,omitempty"`
	Vendor      *string `json:"vendor,omitempty"`
	Device      *string `json:"device,omitempty"`
	Path        *string `json:"path,omitempty"`
	NumaNode    *int32  `json:"numaNode,omitempty"`
	Description *string `json:"description,omitempty"`
	Slot        *string `json:"slot,omitempty"`
}

// NewMachineInfiniBandInterface instantiates a new MachineInfiniBandInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineInfiniBandInterface() *MachineInfiniBandInterface {
	this := MachineInfiniBandInterface{}
	return &this
}

// NewMachineInfiniBandInterfaceWithDefaults instantiates a new MachineInfiniBandInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineInfiniBandInterfaceWithDefaults() *MachineInfiniBandInterface {
	this := MachineInfiniBandInterface{}
	return &this
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *MachineInfiniBandInterface) SetGuid(v string) {
	o.Guid = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *MachineInfiniBandInterface) SetVendor(v string) {
	o.Vendor = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetDevice() string {
	if o == nil || IsNil(o.Device) {
		var ret string
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given string and assigns it to the Device field.
func (o *MachineInfiniBandInterface) SetDevice(v string) {
	o.Device = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *MachineInfiniBandInterface) SetPath(v string) {
	o.Path = &v
}

// GetNumaNode returns the NumaNode field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetNumaNode() int32 {
	if o == nil || IsNil(o.NumaNode) {
		var ret int32
		return ret
	}
	return *o.NumaNode
}

// GetNumaNodeOk returns a tuple with the NumaNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetNumaNodeOk() (*int32, bool) {
	if o == nil || IsNil(o.NumaNode) {
		return nil, false
	}
	return o.NumaNode, true
}

// HasNumaNode returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasNumaNode() bool {
	if o != nil && !IsNil(o.NumaNode) {
		return true
	}

	return false
}

// SetNumaNode gets a reference to the given int32 and assigns it to the NumaNode field.
func (o *MachineInfiniBandInterface) SetNumaNode(v int32) {
	o.NumaNode = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MachineInfiniBandInterface) SetDescription(v string) {
	o.Description = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *MachineInfiniBandInterface) GetSlot() string {
	if o == nil || IsNil(o.Slot) {
		var ret string
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineInfiniBandInterface) GetSlotOk() (*string, bool) {
	if o == nil || IsNil(o.Slot) {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *MachineInfiniBandInterface) HasSlot() bool {
	if o != nil && !IsNil(o.Slot) {
		return true
	}

	return false
}

// SetSlot gets a reference to the given string and assigns it to the Slot field.
func (o *MachineInfiniBandInterface) SetSlot(v string) {
	o.Slot = &v
}

func (o MachineInfiniBandInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineInfiniBandInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.NumaNode) {
		toSerialize["numaNode"] = o.NumaNode
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Slot) {
		toSerialize["slot"] = o.Slot
	}
	return toSerialize, nil
}

type NullableMachineInfiniBandInterface struct {
	value *MachineInfiniBandInterface
	isSet bool
}

func (v NullableMachineInfiniBandInterface) Get() *MachineInfiniBandInterface {
	return v.value
}

func (v *NullableMachineInfiniBandInterface) Set(val *MachineInfiniBandInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineInfiniBandInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineInfiniBandInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineInfiniBandInterface(val *MachineInfiniBandInterface) *NullableMachineInfiniBandInterface {
	return &NullableMachineInfiniBandInterface{value: val, isSet: true}
}

func (v NullableMachineInfiniBandInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineInfiniBandInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
