/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineDMIData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineDMIData{}

// MachineDMIData Describes DMI data of a Machine
type MachineDMIData struct {
	BoardName     *string `json:"boardName,omitempty"`
	BoardSerial   *string `json:"boardSerial,omitempty"`
	BoardVersion  *string `json:"boardVersion,omitempty"`
	BiosDate      *string `json:"biosDate,omitempty"`
	BiosVersion   *string `json:"biosVersion,omitempty"`
	ProductSerial *string `json:"productSerial,omitempty"`
	ChassisSerial *string `json:"chassisSerial,omitempty"`
}

// NewMachineDMIData instantiates a new MachineDMIData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineDMIData() *MachineDMIData {
	this := MachineDMIData{}
	return &this
}

// NewMachineDMIDataWithDefaults instantiates a new MachineDMIData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineDMIDataWithDefaults() *MachineDMIData {
	this := MachineDMIData{}
	return &this
}

// GetBoardName returns the BoardName field value if set, zero value otherwise.
func (o *MachineDMIData) GetBoardName() string {
	if o == nil || IsNil(o.BoardName) {
		var ret string
		return ret
	}
	return *o.BoardName
}

// GetBoardNameOk returns a tuple with the BoardName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetBoardNameOk() (*string, bool) {
	if o == nil || IsNil(o.BoardName) {
		return nil, false
	}
	return o.BoardName, true
}

// HasBoardName returns a boolean if a field has been set.
func (o *MachineDMIData) HasBoardName() bool {
	if o != nil && !IsNil(o.BoardName) {
		return true
	}

	return false
}

// SetBoardName gets a reference to the given string and assigns it to the BoardName field.
func (o *MachineDMIData) SetBoardName(v string) {
	o.BoardName = &v
}

// GetBoardSerial returns the BoardSerial field value if set, zero value otherwise.
func (o *MachineDMIData) GetBoardSerial() string {
	if o == nil || IsNil(o.BoardSerial) {
		var ret string
		return ret
	}
	return *o.BoardSerial
}

// GetBoardSerialOk returns a tuple with the BoardSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetBoardSerialOk() (*string, bool) {
	if o == nil || IsNil(o.BoardSerial) {
		return nil, false
	}
	return o.BoardSerial, true
}

// HasBoardSerial returns a boolean if a field has been set.
func (o *MachineDMIData) HasBoardSerial() bool {
	if o != nil && !IsNil(o.BoardSerial) {
		return true
	}

	return false
}

// SetBoardSerial gets a reference to the given string and assigns it to the BoardSerial field.
func (o *MachineDMIData) SetBoardSerial(v string) {
	o.BoardSerial = &v
}

// GetBoardVersion returns the BoardVersion field value if set, zero value otherwise.
func (o *MachineDMIData) GetBoardVersion() string {
	if o == nil || IsNil(o.BoardVersion) {
		var ret string
		return ret
	}
	return *o.BoardVersion
}

// GetBoardVersionOk returns a tuple with the BoardVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetBoardVersionOk() (*string, bool) {
	if o == nil || IsNil(o.BoardVersion) {
		return nil, false
	}
	return o.BoardVersion, true
}

// HasBoardVersion returns a boolean if a field has been set.
func (o *MachineDMIData) HasBoardVersion() bool {
	if o != nil && !IsNil(o.BoardVersion) {
		return true
	}

	return false
}

// SetBoardVersion gets a reference to the given string and assigns it to the BoardVersion field.
func (o *MachineDMIData) SetBoardVersion(v string) {
	o.BoardVersion = &v
}

// GetBiosDate returns the BiosDate field value if set, zero value otherwise.
func (o *MachineDMIData) GetBiosDate() string {
	if o == nil || IsNil(o.BiosDate) {
		var ret string
		return ret
	}
	return *o.BiosDate
}

// GetBiosDateOk returns a tuple with the BiosDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetBiosDateOk() (*string, bool) {
	if o == nil || IsNil(o.BiosDate) {
		return nil, false
	}
	return o.BiosDate, true
}

// HasBiosDate returns a boolean if a field has been set.
func (o *MachineDMIData) HasBiosDate() bool {
	if o != nil && !IsNil(o.BiosDate) {
		return true
	}

	return false
}

// SetBiosDate gets a reference to the given string and assigns it to the BiosDate field.
func (o *MachineDMIData) SetBiosDate(v string) {
	o.BiosDate = &v
}

// GetBiosVersion returns the BiosVersion field value if set, zero value otherwise.
func (o *MachineDMIData) GetBiosVersion() string {
	if o == nil || IsNil(o.BiosVersion) {
		var ret string
		return ret
	}
	return *o.BiosVersion
}

// GetBiosVersionOk returns a tuple with the BiosVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetBiosVersionOk() (*string, bool) {
	if o == nil || IsNil(o.BiosVersion) {
		return nil, false
	}
	return o.BiosVersion, true
}

// HasBiosVersion returns a boolean if a field has been set.
func (o *MachineDMIData) HasBiosVersion() bool {
	if o != nil && !IsNil(o.BiosVersion) {
		return true
	}

	return false
}

// SetBiosVersion gets a reference to the given string and assigns it to the BiosVersion field.
func (o *MachineDMIData) SetBiosVersion(v string) {
	o.BiosVersion = &v
}

// GetProductSerial returns the ProductSerial field value if set, zero value otherwise.
func (o *MachineDMIData) GetProductSerial() string {
	if o == nil || IsNil(o.ProductSerial) {
		var ret string
		return ret
	}
	return *o.ProductSerial
}

// GetProductSerialOk returns a tuple with the ProductSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetProductSerialOk() (*string, bool) {
	if o == nil || IsNil(o.ProductSerial) {
		return nil, false
	}
	return o.ProductSerial, true
}

// HasProductSerial returns a boolean if a field has been set.
func (o *MachineDMIData) HasProductSerial() bool {
	if o != nil && !IsNil(o.ProductSerial) {
		return true
	}

	return false
}

// SetProductSerial gets a reference to the given string and assigns it to the ProductSerial field.
func (o *MachineDMIData) SetProductSerial(v string) {
	o.ProductSerial = &v
}

// GetChassisSerial returns the ChassisSerial field value if set, zero value otherwise.
func (o *MachineDMIData) GetChassisSerial() string {
	if o == nil || IsNil(o.ChassisSerial) {
		var ret string
		return ret
	}
	return *o.ChassisSerial
}

// GetChassisSerialOk returns a tuple with the ChassisSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineDMIData) GetChassisSerialOk() (*string, bool) {
	if o == nil || IsNil(o.ChassisSerial) {
		return nil, false
	}
	return o.ChassisSerial, true
}

// HasChassisSerial returns a boolean if a field has been set.
func (o *MachineDMIData) HasChassisSerial() bool {
	if o != nil && !IsNil(o.ChassisSerial) {
		return true
	}

	return false
}

// SetChassisSerial gets a reference to the given string and assigns it to the ChassisSerial field.
func (o *MachineDMIData) SetChassisSerial(v string) {
	o.ChassisSerial = &v
}

func (o MachineDMIData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineDMIData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BoardName) {
		toSerialize["boardName"] = o.BoardName
	}
	if !IsNil(o.BoardSerial) {
		toSerialize["boardSerial"] = o.BoardSerial
	}
	if !IsNil(o.BoardVersion) {
		toSerialize["boardVersion"] = o.BoardVersion
	}
	if !IsNil(o.BiosDate) {
		toSerialize["biosDate"] = o.BiosDate
	}
	if !IsNil(o.BiosVersion) {
		toSerialize["biosVersion"] = o.BiosVersion
	}
	if !IsNil(o.ProductSerial) {
		toSerialize["productSerial"] = o.ProductSerial
	}
	if !IsNil(o.ChassisSerial) {
		toSerialize["chassisSerial"] = o.ChassisSerial
	}
	return toSerialize, nil
}

type NullableMachineDMIData struct {
	value *MachineDMIData
	isSet bool
}

func (v NullableMachineDMIData) Get() *MachineDMIData {
	return v.value
}

func (v *NullableMachineDMIData) Set(val *MachineDMIData) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineDMIData) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineDMIData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineDMIData(val *MachineDMIData) *NullableMachineDMIData {
	return &NullableMachineDMIData{value: val, isSet: true}
}

func (v NullableMachineDMIData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineDMIData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
