/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchTrayFirmwareUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchTrayFirmwareUpdateRequest{}

// BatchTrayFirmwareUpdateRequest Request body for batch tray firmware update operations
type BatchTrayFirmwareUpdateRequest struct {
	// ID of the Site
	SiteId string      `json:"siteId"`
	Filter *TrayFilter `json:"filter,omitempty"`
	// Target firmware version.
	Version *string `json:"version,omitempty"`
}

type _BatchTrayFirmwareUpdateRequest BatchTrayFirmwareUpdateRequest

// NewBatchTrayFirmwareUpdateRequest instantiates a new BatchTrayFirmwareUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchTrayFirmwareUpdateRequest(siteId string) *BatchTrayFirmwareUpdateRequest {
	this := BatchTrayFirmwareUpdateRequest{}
	this.SiteId = siteId
	return &this
}

// NewBatchTrayFirmwareUpdateRequestWithDefaults instantiates a new BatchTrayFirmwareUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchTrayFirmwareUpdateRequestWithDefaults() *BatchTrayFirmwareUpdateRequest {
	this := BatchTrayFirmwareUpdateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BatchTrayFirmwareUpdateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BatchTrayFirmwareUpdateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BatchTrayFirmwareUpdateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *BatchTrayFirmwareUpdateRequest) GetFilter() TrayFilter {
	if o == nil || IsNil(o.Filter) {
		var ret TrayFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchTrayFirmwareUpdateRequest) GetFilterOk() (*TrayFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *BatchTrayFirmwareUpdateRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given TrayFilter and assigns it to the Filter field.
func (o *BatchTrayFirmwareUpdateRequest) SetFilter(v TrayFilter) {
	o.Filter = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *BatchTrayFirmwareUpdateRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchTrayFirmwareUpdateRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *BatchTrayFirmwareUpdateRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *BatchTrayFirmwareUpdateRequest) SetVersion(v string) {
	o.Version = &v
}

func (o BatchTrayFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchTrayFirmwareUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *BatchTrayFirmwareUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchTrayFirmwareUpdateRequest := _BatchTrayFirmwareUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchTrayFirmwareUpdateRequest)

	if err != nil {
		return err
	}

	*o = BatchTrayFirmwareUpdateRequest(varBatchTrayFirmwareUpdateRequest)

	return err
}

type NullableBatchTrayFirmwareUpdateRequest struct {
	value *BatchTrayFirmwareUpdateRequest
	isSet bool
}

func (v NullableBatchTrayFirmwareUpdateRequest) Get() *BatchTrayFirmwareUpdateRequest {
	return v.value
}

func (v *NullableBatchTrayFirmwareUpdateRequest) Set(val *BatchTrayFirmwareUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchTrayFirmwareUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchTrayFirmwareUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchTrayFirmwareUpdateRequest(val *BatchTrayFirmwareUpdateRequest) *NullableBatchTrayFirmwareUpdateRequest {
	return &NullableBatchTrayFirmwareUpdateRequest{value: val, isSet: true}
}

func (v NullableBatchTrayFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchTrayFirmwareUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
