/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineBMCInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineBMCInfo{}

// MachineBMCInfo Describes BMC information of a Machine
type MachineBMCInfo struct {
	Ip               *string `json:"ip,omitempty"`
	Mac              *string `json:"mac,omitempty"`
	Version          *string `json:"version,omitempty"`
	FirmwareRevision *string `json:"firmwareRevision,omitempty"`
}

// NewMachineBMCInfo instantiates a new MachineBMCInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineBMCInfo() *MachineBMCInfo {
	this := MachineBMCInfo{}
	return &this
}

// NewMachineBMCInfoWithDefaults instantiates a new MachineBMCInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineBMCInfoWithDefaults() *MachineBMCInfo {
	this := MachineBMCInfo{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *MachineBMCInfo) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineBMCInfo) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *MachineBMCInfo) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *MachineBMCInfo) SetIp(v string) {
	o.Ip = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *MachineBMCInfo) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineBMCInfo) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *MachineBMCInfo) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *MachineBMCInfo) SetMac(v string) {
	o.Mac = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MachineBMCInfo) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineBMCInfo) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MachineBMCInfo) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *MachineBMCInfo) SetVersion(v string) {
	o.Version = &v
}

// GetFirmwareRevision returns the FirmwareRevision field value if set, zero value otherwise.
func (o *MachineBMCInfo) GetFirmwareRevision() string {
	if o == nil || IsNil(o.FirmwareRevision) {
		var ret string
		return ret
	}
	return *o.FirmwareRevision
}

// GetFirmwareRevisionOk returns a tuple with the FirmwareRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineBMCInfo) GetFirmwareRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.FirmwareRevision) {
		return nil, false
	}
	return o.FirmwareRevision, true
}

// HasFirmwareRevision returns a boolean if a field has been set.
func (o *MachineBMCInfo) HasFirmwareRevision() bool {
	if o != nil && !IsNil(o.FirmwareRevision) {
		return true
	}

	return false
}

// SetFirmwareRevision gets a reference to the given string and assigns it to the FirmwareRevision field.
func (o *MachineBMCInfo) SetFirmwareRevision(v string) {
	o.FirmwareRevision = &v
}

func (o MachineBMCInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineBMCInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.FirmwareRevision) {
		toSerialize["firmwareRevision"] = o.FirmwareRevision
	}
	return toSerialize, nil
}

type NullableMachineBMCInfo struct {
	value *MachineBMCInfo
	isSet bool
}

func (v NullableMachineBMCInfo) Get() *MachineBMCInfo {
	return v.value
}

func (v *NullableMachineBMCInfo) Set(val *MachineBMCInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineBMCInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineBMCInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineBMCInfo(val *MachineBMCInfo) *NullableMachineBMCInfo {
	return &NullableMachineBMCInfo{value: val, isSet: true}
}

func (v NullableMachineBMCInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineBMCInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
