/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AllocationCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllocationCreateRequest{}

// AllocationCreateRequest Request data to create an Allocation
type AllocationCreateRequest struct {
	Name                  string                              `json:"name"`
	Description           *string                             `json:"description,omitempty"`
	TenantId              string                              `json:"tenantId"`
	SiteId                string                              `json:"siteId"`
	AllocationConstraints []AllocationConstraintCreateRequest `json:"allocationConstraints,omitempty"`
}

type _AllocationCreateRequest AllocationCreateRequest

// NewAllocationCreateRequest instantiates a new AllocationCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllocationCreateRequest(name string, tenantId string, siteId string) *AllocationCreateRequest {
	this := AllocationCreateRequest{}
	this.Name = name
	this.TenantId = tenantId
	this.SiteId = siteId
	return &this
}

// NewAllocationCreateRequestWithDefaults instantiates a new AllocationCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllocationCreateRequestWithDefaults() *AllocationCreateRequest {
	this := AllocationCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *AllocationCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AllocationCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AllocationCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AllocationCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AllocationCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AllocationCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTenantId returns the TenantId field value
func (o *AllocationCreateRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AllocationCreateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AllocationCreateRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetSiteId returns the SiteId field value
func (o *AllocationCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *AllocationCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *AllocationCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetAllocationConstraints returns the AllocationConstraints field value if set, zero value otherwise.
func (o *AllocationCreateRequest) GetAllocationConstraints() []AllocationConstraintCreateRequest {
	if o == nil || IsNil(o.AllocationConstraints) {
		var ret []AllocationConstraintCreateRequest
		return ret
	}
	return o.AllocationConstraints
}

// GetAllocationConstraintsOk returns a tuple with the AllocationConstraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationCreateRequest) GetAllocationConstraintsOk() ([]AllocationConstraintCreateRequest, bool) {
	if o == nil || IsNil(o.AllocationConstraints) {
		return nil, false
	}
	return o.AllocationConstraints, true
}

// HasAllocationConstraints returns a boolean if a field has been set.
func (o *AllocationCreateRequest) HasAllocationConstraints() bool {
	if o != nil && !IsNil(o.AllocationConstraints) {
		return true
	}

	return false
}

// SetAllocationConstraints gets a reference to the given []AllocationConstraintCreateRequest and assigns it to the AllocationConstraints field.
func (o *AllocationCreateRequest) SetAllocationConstraints(v []AllocationConstraintCreateRequest) {
	o.AllocationConstraints = v
}

func (o AllocationCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllocationCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.AllocationConstraints) {
		toSerialize["allocationConstraints"] = o.AllocationConstraints
	}
	return toSerialize, nil
}

func (o *AllocationCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"tenantId",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAllocationCreateRequest := _AllocationCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAllocationCreateRequest)

	if err != nil {
		return err
	}

	*o = AllocationCreateRequest(varAllocationCreateRequest)

	return err
}

type NullableAllocationCreateRequest struct {
	value *AllocationCreateRequest
	isSet bool
}

func (v NullableAllocationCreateRequest) Get() *AllocationCreateRequest {
	return v.value
}

func (v *NullableAllocationCreateRequest) Set(val *AllocationCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocationCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocationCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocationCreateRequest(val *AllocationCreateRequest) *NullableAllocationCreateRequest {
	return &NullableAllocationCreateRequest{value: val, isSet: true}
}

func (v NullableAllocationCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocationCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
