/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineHealthIssue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineHealthIssue{}

// MachineHealthIssue Data describing health issue with a Machine
type MachineHealthIssue struct {
	// Category of the issue
	Category *string `json:"category,omitempty"`
	// Short summary describing the issue
	Summary *string `json:"summary,omitempty"`
	// Details about the issue helpful for diagnosis
	Details NullableString `json:"details,omitempty"`
}

// NewMachineHealthIssue instantiates a new MachineHealthIssue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineHealthIssue() *MachineHealthIssue {
	this := MachineHealthIssue{}
	return &this
}

// NewMachineHealthIssueWithDefaults instantiates a new MachineHealthIssue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineHealthIssueWithDefaults() *MachineHealthIssue {
	this := MachineHealthIssue{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *MachineHealthIssue) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthIssue) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *MachineHealthIssue) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *MachineHealthIssue) SetCategory(v string) {
	o.Category = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *MachineHealthIssue) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineHealthIssue) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *MachineHealthIssue) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *MachineHealthIssue) SetSummary(v string) {
	o.Summary = &v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineHealthIssue) GetDetails() string {
	if o == nil || IsNil(o.Details.Get()) {
		var ret string
		return ret
	}
	return *o.Details.Get()
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineHealthIssue) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details.Get(), o.Details.IsSet()
}

// HasDetails returns a boolean if a field has been set.
func (o *MachineHealthIssue) HasDetails() bool {
	if o != nil && o.Details.IsSet() {
		return true
	}

	return false
}

// SetDetails gets a reference to the given NullableString and assigns it to the Details field.
func (o *MachineHealthIssue) SetDetails(v string) {
	o.Details.Set(&v)
}

// SetDetailsNil sets the value for Details to be an explicit nil
func (o *MachineHealthIssue) SetDetailsNil() {
	o.Details.Set(nil)
}

// UnsetDetails ensures that no value is present for Details, not even an explicit nil
func (o *MachineHealthIssue) UnsetDetails() {
	o.Details.Unset()
}

func (o MachineHealthIssue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineHealthIssue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if o.Details.IsSet() {
		toSerialize["details"] = o.Details.Get()
	}
	return toSerialize, nil
}

type NullableMachineHealthIssue struct {
	value *MachineHealthIssue
	isSet bool
}

func (v NullableMachineHealthIssue) Get() *MachineHealthIssue {
	return v.value
}

func (v *NullableMachineHealthIssue) Set(val *MachineHealthIssue) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineHealthIssue) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineHealthIssue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineHealthIssue(val *MachineHealthIssue) *NullableMachineHealthIssue {
	return &NullableMachineHealthIssue{value: val, isSet: true}
}

func (v NullableMachineHealthIssue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineHealthIssue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
