/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CarbideAPIError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CarbideAPIError{}

// CarbideAPIError Describes the error response from NCX Infra Controller REST API
type CarbideAPIError struct {
	// Source of the error. Only 'carbide' is supported
	Source *string `json:"source,omitempty"`
	// Message describing the error
	Message *string `json:"message,omitempty"`
	// Additional data about the error
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewCarbideAPIError instantiates a new CarbideAPIError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCarbideAPIError() *CarbideAPIError {
	this := CarbideAPIError{}
	return &this
}

// NewCarbideAPIErrorWithDefaults instantiates a new CarbideAPIError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCarbideAPIErrorWithDefaults() *CarbideAPIError {
	this := CarbideAPIError{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CarbideAPIError) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarbideAPIError) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CarbideAPIError) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *CarbideAPIError) SetSource(v string) {
	o.Source = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CarbideAPIError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarbideAPIError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CarbideAPIError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CarbideAPIError) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CarbideAPIError) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CarbideAPIError) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CarbideAPIError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *CarbideAPIError) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o CarbideAPIError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CarbideAPIError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCarbideAPIError struct {
	value *CarbideAPIError
	isSet bool
}

func (v NullableCarbideAPIError) Get() *CarbideAPIError {
	return v.value
}

func (v *NullableCarbideAPIError) Set(val *CarbideAPIError) {
	v.value = val
	v.isSet = true
}

func (v NullableCarbideAPIError) IsSet() bool {
	return v.isSet
}

func (v *NullableCarbideAPIError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCarbideAPIError(val *CarbideAPIError) *NullableCarbideAPIError {
	return &NullableCarbideAPIError{value: val, isSet: true}
}

func (v NullableCarbideAPIError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCarbideAPIError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
