/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DpuExtensionServiceUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceUpdateRequest{}

// DpuExtensionServiceUpdateRequest Request data to update an existing DPU Extension Service
type DpuExtensionServiceUpdateRequest struct {
	// Name for the DPU Extension Service. Must be unique for a given Tenant
	Name *string `json:"name,omitempty"`
	// Optional description for the DPU Extension Service
	Description *string `json:"description,omitempty"`
	// Deployment spec for the DPU Extension Service
	Data *string `json:"data,omitempty"`
	// Credentials to download resources specified in DPU Extension Service data
	Credentials *DpuExtensionServiceCredentials `json:"credentials,omitempty"`
}

// NewDpuExtensionServiceUpdateRequest instantiates a new DpuExtensionServiceUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceUpdateRequest() *DpuExtensionServiceUpdateRequest {
	this := DpuExtensionServiceUpdateRequest{}
	return &this
}

// NewDpuExtensionServiceUpdateRequestWithDefaults instantiates a new DpuExtensionServiceUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceUpdateRequestWithDefaults() *DpuExtensionServiceUpdateRequest {
	this := DpuExtensionServiceUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DpuExtensionServiceUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DpuExtensionServiceUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DpuExtensionServiceUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DpuExtensionServiceUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DpuExtensionServiceUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DpuExtensionServiceUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DpuExtensionServiceUpdateRequest) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceUpdateRequest) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DpuExtensionServiceUpdateRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *DpuExtensionServiceUpdateRequest) SetData(v string) {
	o.Data = &v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *DpuExtensionServiceUpdateRequest) GetCredentials() DpuExtensionServiceCredentials {
	if o == nil || IsNil(o.Credentials) {
		var ret DpuExtensionServiceCredentials
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuExtensionServiceUpdateRequest) GetCredentialsOk() (*DpuExtensionServiceCredentials, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *DpuExtensionServiceUpdateRequest) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given DpuExtensionServiceCredentials and assigns it to the Credentials field.
func (o *DpuExtensionServiceUpdateRequest) SetCredentials(v DpuExtensionServiceCredentials) {
	o.Credentials = &v
}

func (o DpuExtensionServiceUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableDpuExtensionServiceUpdateRequest struct {
	value *DpuExtensionServiceUpdateRequest
	isSet bool
}

func (v NullableDpuExtensionServiceUpdateRequest) Get() *DpuExtensionServiceUpdateRequest {
	return v.value
}

func (v *NullableDpuExtensionServiceUpdateRequest) Set(val *DpuExtensionServiceUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceUpdateRequest(val *DpuExtensionServiceUpdateRequest) *NullableDpuExtensionServiceUpdateRequest {
	return &NullableDpuExtensionServiceUpdateRequest{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
