// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: expectedswitch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExpectedSwitchInventory - inventory info of all ExpectedSwitches on Site collected
// periodically
type ExpectedSwitchInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,1,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	// Status message
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Reported timestamp of Expected Switch inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// List of Expected Switches
	ExpectedSwitches []*ExpectedSwitch `protobuf:"bytes,4,rep,name=expected_switches,json=expectedSwitches,proto3" json:"expected_switches,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	// Linked Expected Switches (contains Switch ID)
	LinkedSwitches []*LinkedExpectedSwitch `protobuf:"bytes,6,rep,name=linked_switches,json=linkedSwitches,proto3" json:"linked_switches,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExpectedSwitchInventory) Reset() {
	*x = ExpectedSwitchInventory{}
	mi := &file_expectedswitch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpectedSwitchInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpectedSwitchInventory) ProtoMessage() {}

func (x *ExpectedSwitchInventory) ProtoReflect() protoreflect.Message {
	mi := &file_expectedswitch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpectedSwitchInventory.ProtoReflect.Descriptor instead.
func (*ExpectedSwitchInventory) Descriptor() ([]byte, []int) {
	return file_expectedswitch_proto_rawDescGZIP(), []int{0}
}

func (x *ExpectedSwitchInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *ExpectedSwitchInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ExpectedSwitchInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExpectedSwitchInventory) GetExpectedSwitches() []*ExpectedSwitch {
	if x != nil {
		return x.ExpectedSwitches
	}
	return nil
}

func (x *ExpectedSwitchInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

func (x *ExpectedSwitchInventory) GetLinkedSwitches() []*LinkedExpectedSwitch {
	if x != nil {
		return x.LinkedSwitches
	}
	return nil
}

var File_expectedswitch_proto protoreflect.FileDescriptor

const file_expectedswitch_proto_rawDesc = "" +
	"\n" +
	"\x14expectedswitch.proto\x12\fworkflows.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eworkflow.proto\x1a\x14common_carbide.proto\x1a\x13forge_carbide.proto\"\x8a\x03\n" +
	"\x17ExpectedSwitchInventory\x12H\n" +
	"\x10inventory_status\x18\x01 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\x11expected_switches\x18\x04 \x03(\v2\x15.forge.ExpectedSwitchR\x10expectedSwitches\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPage\x12D\n" +
	"\x0flinked_switches\x18\x06 \x03(\v2\x1b.forge.LinkedExpectedSwitchR\x0elinkedSwitchesBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_expectedswitch_proto_rawDescOnce sync.Once
	file_expectedswitch_proto_rawDescData []byte
)

func file_expectedswitch_proto_rawDescGZIP() []byte {
	file_expectedswitch_proto_rawDescOnce.Do(func() {
		file_expectedswitch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expectedswitch_proto_rawDesc), len(file_expectedswitch_proto_rawDesc)))
	})
	return file_expectedswitch_proto_rawDescData
}

var file_expectedswitch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_expectedswitch_proto_goTypes = []any{
	(*ExpectedSwitchInventory)(nil), // 0: workflows.v1.ExpectedSwitchInventory
	(InventoryStatus)(0),            // 1: workflows.v1.InventoryStatus
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
	(*ExpectedSwitch)(nil),          // 3: forge.ExpectedSwitch
	(*InventoryPage)(nil),           // 4: workflows.v1.InventoryPage
	(*LinkedExpectedSwitch)(nil),    // 5: forge.LinkedExpectedSwitch
}
var file_expectedswitch_proto_depIdxs = []int32{
	1, // 0: workflows.v1.ExpectedSwitchInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	2, // 1: workflows.v1.ExpectedSwitchInventory.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: workflows.v1.ExpectedSwitchInventory.expected_switches:type_name -> forge.ExpectedSwitch
	4, // 3: workflows.v1.ExpectedSwitchInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	5, // 4: workflows.v1.ExpectedSwitchInventory.linked_switches:type_name -> forge.LinkedExpectedSwitch
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_expectedswitch_proto_init() }
func file_expectedswitch_proto_init() {
	if File_expectedswitch_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_common_carbide_proto_init()
	file_forge_carbide_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expectedswitch_proto_rawDesc), len(file_expectedswitch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expectedswitch_proto_goTypes,
		DependencyIndexes: file_expectedswitch_proto_depIdxs,
		MessageInfos:      file_expectedswitch_proto_msgTypes,
	}.Build()
	File_expectedswitch_proto = out.File
	file_expectedswitch_proto_goTypes = nil
	file_expectedswitch_proto_depIdxs = nil
}
