// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthState - possible health status for a given state
type HealthState int32

const (
	HealthState_UNKNOWN HealthState = 0
	HealthState_UP      HealthState = 1
	HealthState_DOWN    HealthState = 2
	HealthState_ERROR   HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "UNKNOWN",
		1: "UP",
		2: "DOWN",
		3: "ERROR",
	}
	HealthState_value = map[string]int32{
		"UNKNOWN": 0,
		"UP":      1,
		"DOWN":    2,
		"ERROR":   3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// HealthStatus - site agent health status info sent to cloud
type HealthStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Site Inventory collection status via Cron
	SiteInventoryCollection *HealthStatusMsg `protobuf:"bytes,1,opt,name=SiteInventoryCollection,proto3" json:"SiteInventoryCollection,omitempty"`
	// Site GRPC interface connection status
	SiteControllerConnection *HealthStatusMsg `protobuf:"bytes,2,opt,name=SiteControllerConnection,proto3" json:"SiteControllerConnection,omitempty"`
	// Site Agent HA Status
	SiteAgentHighAvailability *HealthStatusMsg `protobuf:"bytes,3,opt,name=SiteAgentHighAvailability,proto3" json:"SiteAgentHighAvailability,omitempty"`
	// Reported timestamp of Health status
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthStatus) GetSiteInventoryCollection() *HealthStatusMsg {
	if x != nil {
		return x.SiteInventoryCollection
	}
	return nil
}

func (x *HealthStatus) GetSiteControllerConnection() *HealthStatusMsg {
	if x != nil {
		return x.SiteControllerConnection
	}
	return nil
}

func (x *HealthStatus) GetSiteAgentHighAvailability() *HealthStatusMsg {
	if x != nil {
		return x.SiteAgentHighAvailability
	}
	return nil
}

func (x *HealthStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthStatusMsg - status of given state in Site agent
type HealthStatusMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         HealthState            `protobuf:"varint,1,opt,name=State,proto3,enum=workflows.v1.HealthState" json:"State,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusMsg) Reset() {
	*x = HealthStatusMsg{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusMsg) ProtoMessage() {}

func (x *HealthStatusMsg) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusMsg.ProtoReflect.Descriptor instead.
func (*HealthStatusMsg) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatusMsg) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_UNKNOWN
}

func (x *HealthStatusMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\fworkflows.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\fHealthStatus\x12W\n" +
	"\x17SiteInventoryCollection\x18\x01 \x01(\v2\x1d.workflows.v1.HealthStatusMsgR\x17SiteInventoryCollection\x12Y\n" +
	"\x18SiteControllerConnection\x18\x02 \x01(\v2\x1d.workflows.v1.HealthStatusMsgR\x18SiteControllerConnection\x12[\n" +
	"\x19SiteAgentHighAvailability\x18\x03 \x01(\v2\x1d.workflows.v1.HealthStatusMsgR\x19SiteAgentHighAvailability\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"d\n" +
	"\x0fHealthStatusMsg\x12/\n" +
	"\x05State\x18\x01 \x01(\x0e2\x19.workflows.v1.HealthStateR\x05State\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription*7\n" +
	"\vHealthState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\x12\b\n" +
	"\x04DOWN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03BCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_health_proto_goTypes = []any{
	(HealthState)(0),              // 0: workflows.v1.HealthState
	(*HealthStatus)(nil),          // 1: workflows.v1.HealthStatus
	(*HealthStatusMsg)(nil),       // 2: workflows.v1.HealthStatusMsg
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_health_proto_depIdxs = []int32{
	2, // 0: workflows.v1.HealthStatus.SiteInventoryCollection:type_name -> workflows.v1.HealthStatusMsg
	2, // 1: workflows.v1.HealthStatus.SiteControllerConnection:type_name -> workflows.v1.HealthStatusMsg
	2, // 2: workflows.v1.HealthStatus.SiteAgentHighAvailability:type_name -> workflows.v1.HealthStatusMsg
	3, // 3: workflows.v1.HealthStatus.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: workflows.v1.HealthStatusMsg.State:type_name -> workflows.v1.HealthState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
