// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infiniband_partition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateInfiniBandPartitionRequest - request parameters for InfiniBandPartition creation
type CreateInfiniBandPartitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the partition
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID of the Tenant org creating this Partition
	TenantOrganizationId string `protobuf:"bytes,2,opt,name=tenant_organization_id,json=tenantOrganizationId,proto3" json:"tenant_organization_id,omitempty"`
	// Workflow configurations
	Options *WorkflowOptions `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// ID of the partition
	IbPartitionId *UUID `protobuf:"bytes,4,opt,name=ib_partition_id,json=ibPartitionId,proto3" json:"ib_partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInfiniBandPartitionRequest) Reset() {
	*x = CreateInfiniBandPartitionRequest{}
	mi := &file_infiniband_partition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInfiniBandPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInfiniBandPartitionRequest) ProtoMessage() {}

func (x *CreateInfiniBandPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infiniband_partition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInfiniBandPartitionRequest.ProtoReflect.Descriptor instead.
func (*CreateInfiniBandPartitionRequest) Descriptor() ([]byte, []int) {
	return file_infiniband_partition_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInfiniBandPartitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInfiniBandPartitionRequest) GetTenantOrganizationId() string {
	if x != nil {
		return x.TenantOrganizationId
	}
	return ""
}

func (x *CreateInfiniBandPartitionRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateInfiniBandPartitionRequest) GetIbPartitionId() *UUID {
	if x != nil {
		return x.IbPartitionId
	}
	return nil
}

// DeleteInfiniBandPartitionRequest - request parameters to delete InfiniBandPartition
type DeleteInfiniBandPartitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the InfiniBandPartition to be deleted
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Workflow configurations
	Options       *WorkflowOptions `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInfiniBandPartitionRequest) Reset() {
	*x = DeleteInfiniBandPartitionRequest{}
	mi := &file_infiniband_partition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInfiniBandPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInfiniBandPartitionRequest) ProtoMessage() {}

func (x *DeleteInfiniBandPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infiniband_partition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInfiniBandPartitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteInfiniBandPartitionRequest) Descriptor() ([]byte, []int) {
	return file_infiniband_partition_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteInfiniBandPartitionRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeleteInfiniBandPartitionRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetInfiniBandPartition - request to get a specific InfiniBandPartition
type GetInfiniBandPartitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the InfiniBandPartition to be deleted
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Workflow configurations
	Options       *WorkflowOptions `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfiniBandPartitionRequest) Reset() {
	*x = GetInfiniBandPartitionRequest{}
	mi := &file_infiniband_partition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfiniBandPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfiniBandPartitionRequest) ProtoMessage() {}

func (x *GetInfiniBandPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infiniband_partition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfiniBandPartitionRequest.ProtoReflect.Descriptor instead.
func (*GetInfiniBandPartitionRequest) Descriptor() ([]byte, []int) {
	return file_infiniband_partition_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfiniBandPartitionRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetInfiniBandPartitionRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// InfiniBandPartitionInfo - response for InfiniBandPartition create/update/delete request
type InfiniBandPartitionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of workflow execution
	Status WorkflowStatus `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	// Status if the object, if available
	ObjectStatus ObjectStatus `protobuf:"varint,2,opt,name=object_status,json=objectStatus,proto3,enum=workflows.v1.ObjectStatus" json:"object_status,omitempty"`
	// Status message
	StatusMsg string `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Details of the InfiniBandPartition
	IbPartition   *IBPartition `protobuf:"bytes,4,opt,name=ib_partition,json=ibPartition,proto3" json:"ib_partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfiniBandPartitionInfo) Reset() {
	*x = InfiniBandPartitionInfo{}
	mi := &file_infiniband_partition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfiniBandPartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfiniBandPartitionInfo) ProtoMessage() {}

func (x *InfiniBandPartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_infiniband_partition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfiniBandPartitionInfo.ProtoReflect.Descriptor instead.
func (*InfiniBandPartitionInfo) Descriptor() ([]byte, []int) {
	return file_infiniband_partition_proto_rawDescGZIP(), []int{3}
}

func (x *InfiniBandPartitionInfo) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *InfiniBandPartitionInfo) GetObjectStatus() ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return ObjectStatus_OBJECT_STATUS_UNSPECIFIED
}

func (x *InfiniBandPartitionInfo) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *InfiniBandPartitionInfo) GetIbPartition() *IBPartition {
	if x != nil {
		return x.IbPartition
	}
	return nil
}

// InfiniBandPartitionInventory - inventory info of all InfiniBandPartitions on Site collected
// periodically
type InfiniBandPartitionInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,1,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	// Status message
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Reported timestamp of InfiniBand Partition inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// List of InfiniBand Partition
	IbPartitions []*IBPartition `protobuf:"bytes,4,rep,name=ib_partitions,json=ibPartitions,proto3" json:"ib_partitions,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfiniBandPartitionInventory) Reset() {
	*x = InfiniBandPartitionInventory{}
	mi := &file_infiniband_partition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfiniBandPartitionInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfiniBandPartitionInventory) ProtoMessage() {}

func (x *InfiniBandPartitionInventory) ProtoReflect() protoreflect.Message {
	mi := &file_infiniband_partition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfiniBandPartitionInventory.ProtoReflect.Descriptor instead.
func (*InfiniBandPartitionInventory) Descriptor() ([]byte, []int) {
	return file_infiniband_partition_proto_rawDescGZIP(), []int{4}
}

func (x *InfiniBandPartitionInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *InfiniBandPartitionInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *InfiniBandPartitionInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *InfiniBandPartitionInventory) GetIbPartitions() []*IBPartition {
	if x != nil {
		return x.IbPartitions
	}
	return nil
}

func (x *InfiniBandPartitionInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_infiniband_partition_proto protoreflect.FileDescriptor

const file_infiniband_partition_proto_rawDesc = "" +
	"\n" +
	"\x1ainfiniband_partition.proto\x12\fworkflows.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eworkflow.proto\x1a\x14common_carbide.proto\x1a\x13forge_carbide.proto\"\xec\x01\n" +
	" CreateInfiniBandPartitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x16tenant_organization_id\x18\x02 \x01(\tR\x14tenantOrganizationId\x12<\n" +
	"\aoptions\x18\x03 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01\x124\n" +
	"\x0fib_partition_id\x18\x04 \x01(\v2\f.common.UUIDR\ribPartitionIdB\n" +
	"\n" +
	"\b_options\"\x8a\x01\n" +
	" DeleteInfiniBandPartitionRequest\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.common.UUIDR\x02id\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\x87\x01\n" +
	"\x1dGetInfiniBandPartitionRequest\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.common.UUIDR\x02id\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xe6\x01\n" +
	"\x17InfiniBandPartitionInfo\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12?\n" +
	"\robject_status\x18\x02 \x01(\x0e2\x1a.workflows.v1.ObjectStatusR\fobjectStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x125\n" +
	"\fib_partition\x18\x04 \x01(\v2\x12.forge.IBPartitionR\vibPartition\"\xbe\x02\n" +
	"\x1cInfiniBandPartitionInventory\x12H\n" +
	"\x10inventory_status\x18\x01 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\rib_partitions\x18\x04 \x03(\v2\x12.forge.IBPartitionR\fibPartitions\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_infiniband_partition_proto_rawDescOnce sync.Once
	file_infiniband_partition_proto_rawDescData []byte
)

func file_infiniband_partition_proto_rawDescGZIP() []byte {
	file_infiniband_partition_proto_rawDescOnce.Do(func() {
		file_infiniband_partition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infiniband_partition_proto_rawDesc), len(file_infiniband_partition_proto_rawDesc)))
	})
	return file_infiniband_partition_proto_rawDescData
}

var file_infiniband_partition_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_infiniband_partition_proto_goTypes = []any{
	(*CreateInfiniBandPartitionRequest)(nil), // 0: workflows.v1.CreateInfiniBandPartitionRequest
	(*DeleteInfiniBandPartitionRequest)(nil), // 1: workflows.v1.DeleteInfiniBandPartitionRequest
	(*GetInfiniBandPartitionRequest)(nil),    // 2: workflows.v1.GetInfiniBandPartitionRequest
	(*InfiniBandPartitionInfo)(nil),          // 3: workflows.v1.InfiniBandPartitionInfo
	(*InfiniBandPartitionInventory)(nil),     // 4: workflows.v1.InfiniBandPartitionInventory
	(*WorkflowOptions)(nil),                  // 5: workflows.v1.WorkflowOptions
	(*UUID)(nil),                             // 6: common.UUID
	(WorkflowStatus)(0),                      // 7: workflows.v1.WorkflowStatus
	(ObjectStatus)(0),                        // 8: workflows.v1.ObjectStatus
	(*IBPartition)(nil),                      // 9: forge.IBPartition
	(InventoryStatus)(0),                     // 10: workflows.v1.InventoryStatus
	(*timestamppb.Timestamp)(nil),            // 11: google.protobuf.Timestamp
	(*InventoryPage)(nil),                    // 12: workflows.v1.InventoryPage
}
var file_infiniband_partition_proto_depIdxs = []int32{
	5,  // 0: workflows.v1.CreateInfiniBandPartitionRequest.options:type_name -> workflows.v1.WorkflowOptions
	6,  // 1: workflows.v1.CreateInfiniBandPartitionRequest.ib_partition_id:type_name -> common.UUID
	6,  // 2: workflows.v1.DeleteInfiniBandPartitionRequest.id:type_name -> common.UUID
	5,  // 3: workflows.v1.DeleteInfiniBandPartitionRequest.options:type_name -> workflows.v1.WorkflowOptions
	6,  // 4: workflows.v1.GetInfiniBandPartitionRequest.id:type_name -> common.UUID
	5,  // 5: workflows.v1.GetInfiniBandPartitionRequest.options:type_name -> workflows.v1.WorkflowOptions
	7,  // 6: workflows.v1.InfiniBandPartitionInfo.status:type_name -> workflows.v1.WorkflowStatus
	8,  // 7: workflows.v1.InfiniBandPartitionInfo.object_status:type_name -> workflows.v1.ObjectStatus
	9,  // 8: workflows.v1.InfiniBandPartitionInfo.ib_partition:type_name -> forge.IBPartition
	10, // 9: workflows.v1.InfiniBandPartitionInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	11, // 10: workflows.v1.InfiniBandPartitionInventory.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 11: workflows.v1.InfiniBandPartitionInventory.ib_partitions:type_name -> forge.IBPartition
	12, // 12: workflows.v1.InfiniBandPartitionInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_infiniband_partition_proto_init() }
func file_infiniband_partition_proto_init() {
	if File_infiniband_partition_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_common_carbide_proto_init()
	file_forge_carbide_proto_init()
	file_infiniband_partition_proto_msgTypes[0].OneofWrappers = []any{}
	file_infiniband_partition_proto_msgTypes[1].OneofWrappers = []any{}
	file_infiniband_partition_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infiniband_partition_proto_rawDesc), len(file_infiniband_partition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infiniband_partition_proto_goTypes,
		DependencyIndexes: file_infiniband_partition_proto_depIdxs,
		MessageInfos:      file_infiniband_partition_proto_msgTypes,
	}.Build()
	File_infiniband_partition_proto = out.File
	file_infiniband_partition_proto_goTypes = nil
	file_infiniband_partition_proto_depIdxs = nil
}
