// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: instance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceInfo - response for instance cloud requests
type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	ObjectStatus  ObjectStatus           `protobuf:"varint,2,opt,name=object_status,json=objectStatus,proto3,enum=workflows.v1.ObjectStatus" json:"object_status,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Instance      *Instance              `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceInfo) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *InstanceInfo) GetObjectStatus() ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return ObjectStatus_OBJECT_STATUS_UNSPECIFIED
}

func (x *InstanceInfo) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *InstanceInfo) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// InstanceUserData
type InstanceUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      string                 `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	CustomIpxe    string                 `protobuf:"bytes,2,opt,name=custom_ipxe,json=customIpxe,proto3" json:"custom_ipxe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceUserData) Reset() {
	*x = InstanceUserData{}
	mi := &file_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceUserData) ProtoMessage() {}

func (x *InstanceUserData) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceUserData.ProtoReflect.Descriptor instead.
func (*InstanceUserData) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceUserData) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *InstanceUserData) GetCustomIpxe() string {
	if x != nil {
		return x.CustomIpxe
	}
	return ""
}

// CreateInstanceRequest - request to create an Instance
type CreateInstanceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId *MachineId             `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Deprecated
	SshKeys    []string                   `protobuf:"bytes,2,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	TenantOrg  string                     `protobuf:"bytes,3,opt,name=tenant_org,json=tenantOrg,proto3" json:"tenant_org,omitempty"`
	Interfaces []*InstanceInterfaceConfig `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	// Optionals
	CustomIpxe *string `protobuf:"bytes,5,opt,name=custom_ipxe,json=customIpxe,proto3,oneof" json:"custom_ipxe,omitempty"`
	UserData   *string `protobuf:"bytes,6,opt,name=user_data,json=userData,proto3,oneof" json:"user_data,omitempty"`
	// Workflow Options
	Options *WorkflowOptions `protobuf:"bytes,7,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// Tenant Keysets for SOL
	TenantKeysetIds          []string `protobuf:"bytes,8,rep,name=tenant_keyset_ids,json=tenantKeysetIds,proto3" json:"tenant_keyset_ids,omitempty"`
	InstanceId               *UUID    `protobuf:"bytes,9,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AlwaysBootWithCustomIpxe *bool    `protobuf:"varint,10,opt,name=always_boot_with_custom_ipxe,json=alwaysBootWithCustomIpxe,proto3,oneof" json:"always_boot_with_custom_ipxe,omitempty"`
	// InfiniBand Interfaces
	IbInterfaces []*InstanceIBInterfaceConfig `protobuf:"bytes,11,rep,name=ib_interfaces,json=ibInterfaces,proto3" json:"ib_interfaces,omitempty"`
	// Instance metadata info with labels configuration
	Metadata *Metadata `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// If this flag is set to true` the instance will not transition to a Ready state until
	// InstancePhoneHomeLastContact is updated
	PhoneHomeEnabled bool `protobuf:"varint,13,opt,name=phone_home_enabled,json=phoneHomeEnabled,proto3" json:"phone_home_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInstanceRequest) GetMachineId() *MachineId {
	if x != nil {
		return x.MachineId
	}
	return nil
}

func (x *CreateInstanceRequest) GetSshKeys() []string {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *CreateInstanceRequest) GetTenantOrg() string {
	if x != nil {
		return x.TenantOrg
	}
	return ""
}

func (x *CreateInstanceRequest) GetInterfaces() []*InstanceInterfaceConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *CreateInstanceRequest) GetCustomIpxe() string {
	if x != nil && x.CustomIpxe != nil {
		return *x.CustomIpxe
	}
	return ""
}

func (x *CreateInstanceRequest) GetUserData() string {
	if x != nil && x.UserData != nil {
		return *x.UserData
	}
	return ""
}

func (x *CreateInstanceRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateInstanceRequest) GetTenantKeysetIds() []string {
	if x != nil {
		return x.TenantKeysetIds
	}
	return nil
}

func (x *CreateInstanceRequest) GetInstanceId() *UUID {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *CreateInstanceRequest) GetAlwaysBootWithCustomIpxe() bool {
	if x != nil && x.AlwaysBootWithCustomIpxe != nil {
		return *x.AlwaysBootWithCustomIpxe
	}
	return false
}

func (x *CreateInstanceRequest) GetIbInterfaces() []*InstanceIBInterfaceConfig {
	if x != nil {
		return x.IbInterfaces
	}
	return nil
}

func (x *CreateInstanceRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateInstanceRequest) GetPhoneHomeEnabled() bool {
	if x != nil {
		return x.PhoneHomeEnabled
	}
	return false
}

// DeleteInstanceRequest - request to delete an Instance
type DeleteInstanceRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId *UUID                  `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Workflow Options
	Options       *WorkflowOptions `protobuf:"bytes,8,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteInstanceRequest) GetInstanceId() *UUID {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *DeleteInstanceRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// RebootInstanceRequest - request for power cycling the machine of the Instance
type RebootInstanceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MachineId          *MachineId             `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	BootWithCustomIpxe bool                   `protobuf:"varint,2,opt,name=boot_with_custom_ipxe,json=bootWithCustomIpxe,proto3" json:"boot_with_custom_ipxe,omitempty"`
	// Workflow Options
	Options *WorkflowOptions `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// If this flag is true, first update will be performed and then host will be rebooted.
	ApplyUpdatesOnReboot bool `protobuf:"varint,4,opt,name=apply_updates_on_reboot,json=applyUpdatesOnReboot,proto3" json:"apply_updates_on_reboot,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RebootInstanceRequest) Reset() {
	*x = RebootInstanceRequest{}
	mi := &file_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootInstanceRequest) ProtoMessage() {}

func (x *RebootInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootInstanceRequest.ProtoReflect.Descriptor instead.
func (*RebootInstanceRequest) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{4}
}

func (x *RebootInstanceRequest) GetMachineId() *MachineId {
	if x != nil {
		return x.MachineId
	}
	return nil
}

func (x *RebootInstanceRequest) GetBootWithCustomIpxe() bool {
	if x != nil {
		return x.BootWithCustomIpxe
	}
	return false
}

func (x *RebootInstanceRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RebootInstanceRequest) GetApplyUpdatesOnReboot() bool {
	if x != nil {
		return x.ApplyUpdatesOnReboot
	}
	return false
}

// InstanceRebootInfo - response for the power cycle request
type InstanceRebootInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	ObjectStatus  ObjectStatus           `protobuf:"varint,2,opt,name=object_status,json=objectStatus,proto3,enum=workflows.v1.ObjectStatus" json:"object_status,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	MachineId     *MachineId             `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRebootInfo) Reset() {
	*x = InstanceRebootInfo{}
	mi := &file_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRebootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRebootInfo) ProtoMessage() {}

func (x *InstanceRebootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRebootInfo.ProtoReflect.Descriptor instead.
func (*InstanceRebootInfo) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{5}
}

func (x *InstanceRebootInfo) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *InstanceRebootInfo) GetObjectStatus() ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return ObjectStatus_OBJECT_STATUS_UNSPECIFIED
}

func (x *InstanceRebootInfo) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *InstanceRebootInfo) GetMachineId() *MachineId {
	if x != nil {
		return x.MachineId
	}
	return nil
}

// InstanceInventory - inventory info of all Instances periodically collected
type InstanceInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Instances
	Instances []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	// List of Instance propagation details
	NetworkSecurityGroupPropagations []*NetworkSecurityGroupPropagationObjectStatus `protobuf:"bytes,6,rep,name=network_security_group_propagations,json=networkSecurityGroupPropagations,proto3" json:"network_security_group_propagations,omitempty"`
	// Reported timestamp of Instance inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,3,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	StatusMsg       string          `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInventory) Reset() {
	*x = InstanceInventory{}
	mi := &file_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInventory) ProtoMessage() {}

func (x *InstanceInventory) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInventory.ProtoReflect.Descriptor instead.
func (*InstanceInventory) Descriptor() ([]byte, []int) {
	return file_instance_proto_rawDescGZIP(), []int{6}
}

func (x *InstanceInventory) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *InstanceInventory) GetNetworkSecurityGroupPropagations() []*NetworkSecurityGroupPropagationObjectStatus {
	if x != nil {
		return x.NetworkSecurityGroupPropagations
	}
	return nil
}

func (x *InstanceInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *InstanceInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *InstanceInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *InstanceInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_instance_proto protoreflect.FileDescriptor

const file_instance_proto_rawDesc = "" +
	"\n" +
	"\x0einstance.proto\x12\fworkflows.v1\x1a\x0eworkflow.proto\x1a\x14common_carbide.proto\x1a\x13forge_carbide.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\fInstanceInfo\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12?\n" +
	"\robject_status\x18\x02 \x01(\x0e2\x1a.workflows.v1.ObjectStatusR\fobjectStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x12+\n" +
	"\binstance\x18\x04 \x01(\v2\x0f.forge.InstanceR\binstance\"P\n" +
	"\x10InstanceUserData\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12\x1f\n" +
	"\vcustom_ipxe\x18\x02 \x01(\tR\n" +
	"customIpxe\"\xd6\x05\n" +
	"\x15CreateInstanceRequest\x120\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\v2\x11.common.MachineIdR\tmachineId\x12\x19\n" +
	"\bssh_keys\x18\x02 \x03(\tR\asshKeys\x12\x1d\n" +
	"\n" +
	"tenant_org\x18\x03 \x01(\tR\ttenantOrg\x12>\n" +
	"\n" +
	"interfaces\x18\x04 \x03(\v2\x1e.forge.InstanceInterfaceConfigR\n" +
	"interfaces\x12$\n" +
	"\vcustom_ipxe\x18\x05 \x01(\tH\x00R\n" +
	"customIpxe\x88\x01\x01\x12 \n" +
	"\tuser_data\x18\x06 \x01(\tH\x01R\buserData\x88\x01\x01\x12<\n" +
	"\aoptions\x18\a \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x02R\aoptions\x88\x01\x01\x12*\n" +
	"\x11tenant_keyset_ids\x18\b \x03(\tR\x0ftenantKeysetIds\x12-\n" +
	"\vinstance_id\x18\t \x01(\v2\f.common.UUIDR\n" +
	"instanceId\x12C\n" +
	"\x1calways_boot_with_custom_ipxe\x18\n" +
	" \x01(\bH\x03R\x18alwaysBootWithCustomIpxe\x88\x01\x01\x12E\n" +
	"\rib_interfaces\x18\v \x03(\v2 .forge.InstanceIBInterfaceConfigR\fibInterfaces\x12+\n" +
	"\bmetadata\x18\f \x01(\v2\x0f.forge.MetadataR\bmetadata\x12,\n" +
	"\x12phone_home_enabled\x18\r \x01(\bR\x10phoneHomeEnabledB\x0e\n" +
	"\f_custom_ipxeB\f\n" +
	"\n" +
	"_user_dataB\n" +
	"\n" +
	"\b_optionsB\x1f\n" +
	"\x1d_always_boot_with_custom_ipxe\"\x90\x01\n" +
	"\x15DeleteInstanceRequest\x12-\n" +
	"\vinstance_id\x18\x01 \x01(\v2\f.common.UUIDR\n" +
	"instanceId\x12<\n" +
	"\aoptions\x18\b \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xfd\x01\n" +
	"\x15RebootInstanceRequest\x120\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\v2\x11.common.MachineIdR\tmachineId\x121\n" +
	"\x15boot_with_custom_ipxe\x18\x02 \x01(\bR\x12bootWithCustomIpxe\x12<\n" +
	"\aoptions\x18\x03 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01\x125\n" +
	"\x17apply_updates_on_reboot\x18\x04 \x01(\bR\x14applyUpdatesOnRebootB\n" +
	"\n" +
	"\b_options\"\xdc\x01\n" +
	"\x12InstanceRebootInfo\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12?\n" +
	"\robject_status\x18\x02 \x01(\x0e2\x1a.workflows.v1.ObjectStatusR\fobjectStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x120\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\v2\x11.common.MachineIdR\tmachineId\"\xad\x03\n" +
	"\x11InstanceInventory\x12-\n" +
	"\tinstances\x18\x01 \x03(\v2\x0f.forge.InstanceR\tinstances\x12\x81\x01\n" +
	"#network_security_group_propagations\x18\x06 \x03(\v22.forge.NetworkSecurityGroupPropagationObjectStatusR networkSecurityGroupPropagations\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x10inventory_status\x18\x03 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_instance_proto_rawDescOnce sync.Once
	file_instance_proto_rawDescData []byte
)

func file_instance_proto_rawDescGZIP() []byte {
	file_instance_proto_rawDescOnce.Do(func() {
		file_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instance_proto_rawDesc), len(file_instance_proto_rawDesc)))
	})
	return file_instance_proto_rawDescData
}

var file_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_instance_proto_goTypes = []any{
	(*InstanceInfo)(nil),                                // 0: workflows.v1.InstanceInfo
	(*InstanceUserData)(nil),                            // 1: workflows.v1.InstanceUserData
	(*CreateInstanceRequest)(nil),                       // 2: workflows.v1.CreateInstanceRequest
	(*DeleteInstanceRequest)(nil),                       // 3: workflows.v1.DeleteInstanceRequest
	(*RebootInstanceRequest)(nil),                       // 4: workflows.v1.RebootInstanceRequest
	(*InstanceRebootInfo)(nil),                          // 5: workflows.v1.InstanceRebootInfo
	(*InstanceInventory)(nil),                           // 6: workflows.v1.InstanceInventory
	(WorkflowStatus)(0),                                 // 7: workflows.v1.WorkflowStatus
	(ObjectStatus)(0),                                   // 8: workflows.v1.ObjectStatus
	(*Instance)(nil),                                    // 9: forge.Instance
	(*MachineId)(nil),                                   // 10: common.MachineId
	(*InstanceInterfaceConfig)(nil),                     // 11: forge.InstanceInterfaceConfig
	(*WorkflowOptions)(nil),                             // 12: workflows.v1.WorkflowOptions
	(*UUID)(nil),                                        // 13: common.UUID
	(*InstanceIBInterfaceConfig)(nil),                   // 14: forge.InstanceIBInterfaceConfig
	(*Metadata)(nil),                                    // 15: forge.Metadata
	(*NetworkSecurityGroupPropagationObjectStatus)(nil), // 16: forge.NetworkSecurityGroupPropagationObjectStatus
	(*timestamppb.Timestamp)(nil),                       // 17: google.protobuf.Timestamp
	(InventoryStatus)(0),                                // 18: workflows.v1.InventoryStatus
	(*InventoryPage)(nil),                               // 19: workflows.v1.InventoryPage
}
var file_instance_proto_depIdxs = []int32{
	7,  // 0: workflows.v1.InstanceInfo.status:type_name -> workflows.v1.WorkflowStatus
	8,  // 1: workflows.v1.InstanceInfo.object_status:type_name -> workflows.v1.ObjectStatus
	9,  // 2: workflows.v1.InstanceInfo.instance:type_name -> forge.Instance
	10, // 3: workflows.v1.CreateInstanceRequest.machine_id:type_name -> common.MachineId
	11, // 4: workflows.v1.CreateInstanceRequest.interfaces:type_name -> forge.InstanceInterfaceConfig
	12, // 5: workflows.v1.CreateInstanceRequest.options:type_name -> workflows.v1.WorkflowOptions
	13, // 6: workflows.v1.CreateInstanceRequest.instance_id:type_name -> common.UUID
	14, // 7: workflows.v1.CreateInstanceRequest.ib_interfaces:type_name -> forge.InstanceIBInterfaceConfig
	15, // 8: workflows.v1.CreateInstanceRequest.metadata:type_name -> forge.Metadata
	13, // 9: workflows.v1.DeleteInstanceRequest.instance_id:type_name -> common.UUID
	12, // 10: workflows.v1.DeleteInstanceRequest.options:type_name -> workflows.v1.WorkflowOptions
	10, // 11: workflows.v1.RebootInstanceRequest.machine_id:type_name -> common.MachineId
	12, // 12: workflows.v1.RebootInstanceRequest.options:type_name -> workflows.v1.WorkflowOptions
	7,  // 13: workflows.v1.InstanceRebootInfo.status:type_name -> workflows.v1.WorkflowStatus
	8,  // 14: workflows.v1.InstanceRebootInfo.object_status:type_name -> workflows.v1.ObjectStatus
	10, // 15: workflows.v1.InstanceRebootInfo.machine_id:type_name -> common.MachineId
	9,  // 16: workflows.v1.InstanceInventory.instances:type_name -> forge.Instance
	16, // 17: workflows.v1.InstanceInventory.network_security_group_propagations:type_name -> forge.NetworkSecurityGroupPropagationObjectStatus
	17, // 18: workflows.v1.InstanceInventory.timestamp:type_name -> google.protobuf.Timestamp
	18, // 19: workflows.v1.InstanceInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	19, // 20: workflows.v1.InstanceInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_instance_proto_init() }
func file_instance_proto_init() {
	if File_instance_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_common_carbide_proto_init()
	file_forge_carbide_proto_init()
	file_instance_proto_msgTypes[2].OneofWrappers = []any{}
	file_instance_proto_msgTypes[3].OneofWrappers = []any{}
	file_instance_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instance_proto_rawDesc), len(file_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instance_proto_goTypes,
		DependencyIndexes: file_instance_proto_depIdxs,
		MessageInfos:      file_instance_proto_msgTypes,
	}.Build()
	File_instance_proto = out.File
	file_instance_proto_goTypes = nil
	file_instance_proto_depIdxs = nil
}
