// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: machine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *Machine               `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	DiscoveryInfo *DiscoveryInfo         `protobuf:"bytes,2,opt,name=discovery_info,json=discoveryInfo,proto3" json:"discovery_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineInfo) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *MachineInfo) GetDiscoveryInfo() *DiscoveryInfo {
	if x != nil {
		return x.DiscoveryInfo
	}
	return nil
}

type DpuMachine struct {
	state            protoimpl.MessageState            `protogen:"open.v1"`
	Machine          *Machine                          `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	DpuNetworkConfig *ManagedHostNetworkConfigResponse `protobuf:"bytes,2,opt,name=dpu_network_config,json=dpuNetworkConfig,proto3" json:"dpu_network_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DpuMachine) Reset() {
	*x = DpuMachine{}
	mi := &file_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpuMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpuMachine) ProtoMessage() {}

func (x *DpuMachine) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpuMachine.ProtoReflect.Descriptor instead.
func (*DpuMachine) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{1}
}

func (x *DpuMachine) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *DpuMachine) GetDpuNetworkConfig() *ManagedHostNetworkConfigResponse {
	if x != nil {
		return x.DpuNetworkConfig
	}
	return nil
}

type MachineInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Machines
	Machines []*MachineInfo `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	// Reported timestamp of machine inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,3,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	// Status message regarding inventory collection, if any
	StatusMsg string `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInventory) Reset() {
	*x = MachineInventory{}
	mi := &file_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInventory) ProtoMessage() {}

func (x *MachineInventory) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInventory.ProtoReflect.Descriptor instead.
func (*MachineInventory) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineInventory) GetMachines() []*MachineInfo {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *MachineInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MachineInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *MachineInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *MachineInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_machine_proto protoreflect.FileDescriptor

const file_machine_proto_rawDesc = "" +
	"\n" +
	"\rmachine.proto\x12\x14workflows.v1.machine\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eworkflow.proto\x1a\x13forge_carbide.proto\x1a\x1fmachine_discovery_carbide.proto\"\x80\x01\n" +
	"\vMachineInfo\x12(\n" +
	"\amachine\x18\x01 \x01(\v2\x0e.forge.MachineR\amachine\x12G\n" +
	"\x0ediscovery_info\x18\x02 \x01(\v2 .machine_discovery.DiscoveryInfoR\rdiscoveryInfo\"\x8d\x01\n" +
	"\n" +
	"DpuMachine\x12(\n" +
	"\amachine\x18\x01 \x01(\v2\x0e.forge.MachineR\amachine\x12U\n" +
	"\x12dpu_network_config\x18\x02 \x01(\v2'.forge.ManagedHostNetworkConfigResponseR\x10dpuNetworkConfig\"\xb8\x02\n" +
	"\x10MachineInventory\x12=\n" +
	"\bmachines\x18\x01 \x03(\v2!.workflows.v1.machine.MachineInfoR\bmachines\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x10inventory_status\x18\x03 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_machine_proto_rawDescOnce sync.Once
	file_machine_proto_rawDescData []byte
)

func file_machine_proto_rawDescGZIP() []byte {
	file_machine_proto_rawDescOnce.Do(func() {
		file_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)))
	})
	return file_machine_proto_rawDescData
}

var file_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_machine_proto_goTypes = []any{
	(*MachineInfo)(nil),                      // 0: workflows.v1.machine.MachineInfo
	(*DpuMachine)(nil),                       // 1: workflows.v1.machine.DpuMachine
	(*MachineInventory)(nil),                 // 2: workflows.v1.machine.MachineInventory
	(*Machine)(nil),                          // 3: forge.Machine
	(*DiscoveryInfo)(nil),                    // 4: machine_discovery.DiscoveryInfo
	(*ManagedHostNetworkConfigResponse)(nil), // 5: forge.ManagedHostNetworkConfigResponse
	(*timestamppb.Timestamp)(nil),            // 6: google.protobuf.Timestamp
	(InventoryStatus)(0),                     // 7: workflows.v1.InventoryStatus
	(*InventoryPage)(nil),                    // 8: workflows.v1.InventoryPage
}
var file_machine_proto_depIdxs = []int32{
	3, // 0: workflows.v1.machine.MachineInfo.machine:type_name -> forge.Machine
	4, // 1: workflows.v1.machine.MachineInfo.discovery_info:type_name -> machine_discovery.DiscoveryInfo
	3, // 2: workflows.v1.machine.DpuMachine.machine:type_name -> forge.Machine
	5, // 3: workflows.v1.machine.DpuMachine.dpu_network_config:type_name -> forge.ManagedHostNetworkConfigResponse
	0, // 4: workflows.v1.machine.MachineInventory.machines:type_name -> workflows.v1.machine.MachineInfo
	6, // 5: workflows.v1.machine.MachineInventory.timestamp:type_name -> google.protobuf.Timestamp
	7, // 6: workflows.v1.machine.MachineInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	8, // 7: workflows.v1.machine.MachineInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_machine_proto_init() }
func file_machine_proto_init() {
	if File_machine_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_forge_carbide_proto_init()
	file_machine_discovery_carbide_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machine_proto_goTypes,
		DependencyIndexes: file_machine_proto_depIdxs,
		MessageInfos:      file_machine_proto_msgTypes,
	}.Build()
	File_machine_proto = out.File
	file_machine_proto_goTypes = nil
	file_machine_proto_depIdxs = nil
}
