// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mlx_device_carbide.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceField represents the available device fields for filtering.
type DeviceField int32

const (
	DeviceField_DEVICE_FIELD_UNSPECIFIED      DeviceField = 0
	DeviceField_DEVICE_FIELD_DEVICE_TYPE      DeviceField = 1
	DeviceField_DEVICE_FIELD_PART_NUMBER      DeviceField = 2
	DeviceField_DEVICE_FIELD_FIRMWARE_VERSION DeviceField = 3
	DeviceField_DEVICE_FIELD_MAC_ADDRESS      DeviceField = 4
	DeviceField_DEVICE_FIELD_DESCRIPTION      DeviceField = 5
	DeviceField_DEVICE_FIELD_PCI_NAME         DeviceField = 6
	DeviceField_DEVICE_FIELD_STATUS           DeviceField = 7
)

// Enum value maps for DeviceField.
var (
	DeviceField_name = map[int32]string{
		0: "DEVICE_FIELD_UNSPECIFIED",
		1: "DEVICE_FIELD_DEVICE_TYPE",
		2: "DEVICE_FIELD_PART_NUMBER",
		3: "DEVICE_FIELD_FIRMWARE_VERSION",
		4: "DEVICE_FIELD_MAC_ADDRESS",
		5: "DEVICE_FIELD_DESCRIPTION",
		6: "DEVICE_FIELD_PCI_NAME",
		7: "DEVICE_FIELD_STATUS",
	}
	DeviceField_value = map[string]int32{
		"DEVICE_FIELD_UNSPECIFIED":      0,
		"DEVICE_FIELD_DEVICE_TYPE":      1,
		"DEVICE_FIELD_PART_NUMBER":      2,
		"DEVICE_FIELD_FIRMWARE_VERSION": 3,
		"DEVICE_FIELD_MAC_ADDRESS":      4,
		"DEVICE_FIELD_DESCRIPTION":      5,
		"DEVICE_FIELD_PCI_NAME":         6,
		"DEVICE_FIELD_STATUS":           7,
	}
)

func (x DeviceField) Enum() *DeviceField {
	p := new(DeviceField)
	*p = x
	return p
}

func (x DeviceField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceField) Descriptor() protoreflect.EnumDescriptor {
	return file_mlx_device_carbide_proto_enumTypes[0].Descriptor()
}

func (DeviceField) Type() protoreflect.EnumType {
	return &file_mlx_device_carbide_proto_enumTypes[0]
}

func (x DeviceField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceField.Descriptor instead.
func (DeviceField) EnumDescriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{0}
}

// MatchMode defines how filter values should be matched against
// device fields.
type MatchMode int32

const (
	MatchMode_MATCH_MODE_UNSPECIFIED MatchMode = 0
	MatchMode_MATCH_MODE_REGEX       MatchMode = 1
	MatchMode_MATCH_MODE_EXACT       MatchMode = 2
	MatchMode_MATCH_MODE_PREFIX      MatchMode = 3
)

// Enum value maps for MatchMode.
var (
	MatchMode_name = map[int32]string{
		0: "MATCH_MODE_UNSPECIFIED",
		1: "MATCH_MODE_REGEX",
		2: "MATCH_MODE_EXACT",
		3: "MATCH_MODE_PREFIX",
	}
	MatchMode_value = map[string]int32{
		"MATCH_MODE_UNSPECIFIED": 0,
		"MATCH_MODE_REGEX":       1,
		"MATCH_MODE_EXACT":       2,
		"MATCH_MODE_PREFIX":      3,
	}
)

func (x MatchMode) Enum() *MatchMode {
	p := new(MatchMode)
	*p = x
	return p
}

func (x MatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mlx_device_carbide_proto_enumTypes[1].Descriptor()
}

func (MatchMode) Type() protoreflect.EnumType {
	return &file_mlx_device_carbide_proto_enumTypes[1]
}

func (x MatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMode.Descriptor instead.
func (MatchMode) EnumDescriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{1}
}

// MlxDeviceReport represents a complete device discovery report
// with metadata and filtered device results.
type MlxDeviceReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hostname is the system hostname where the report was generated.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// timestamp is when the report was generated.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// devices contains the discovered devices matching any applied filters.
	Devices []*MlxDeviceInfo `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	// filters contains the filter set used to generate this report.
	Filters       *DeviceFilterSet `protobuf:"bytes,4,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlxDeviceReport) Reset() {
	*x = MlxDeviceReport{}
	mi := &file_mlx_device_carbide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlxDeviceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlxDeviceReport) ProtoMessage() {}

func (x *MlxDeviceReport) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlxDeviceReport.ProtoReflect.Descriptor instead.
func (*MlxDeviceReport) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{0}
}

func (x *MlxDeviceReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MlxDeviceReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MlxDeviceReport) GetDevices() []*MlxDeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *MlxDeviceReport) GetFilters() *DeviceFilterSet {
	if x != nil {
		return x.Filters
	}
	return nil
}

// MlxDeviceInfo represents detailed information about a Mellanox network device.
type MlxDeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pci_name is the PCI address or MST device path for the device.
	PciName string `protobuf:"bytes,1,opt,name=pci_name,json=pciName,proto3" json:"pci_name,omitempty"`
	// device_type identifies the specific Mellanox device model.
	DeviceType string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// psid (Parameter-Set IDentification) is a 16-ASCII character string
	// embedded in the firmware image which provides a unique identification
	// for the configuration.
	Psid string `protobuf:"bytes,3,opt,name=psid,proto3" json:"psid,omitempty"`
	// device_description provides a human-readable description of the device.
	DeviceDescription string `protobuf:"bytes,4,opt,name=device_description,json=deviceDescription,proto3" json:"device_description,omitempty"`
	// part_number is the manufacturer part number for the device.
	PartNumber string `protobuf:"bytes,5,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	// fw_version_current is the currently installed firmware version.
	FwVersionCurrent string `protobuf:"bytes,6,opt,name=fw_version_current,json=fwVersionCurrent,proto3" json:"fw_version_current,omitempty"`
	// pxe_version_current is the currently installed PXE boot version.
	PxeVersionCurrent string `protobuf:"bytes,7,opt,name=pxe_version_current,json=pxeVersionCurrent,proto3" json:"pxe_version_current,omitempty"`
	// uefi_version_current is the currently installed UEFI boot version.
	UefiVersionCurrent string `protobuf:"bytes,8,opt,name=uefi_version_current,json=uefiVersionCurrent,proto3" json:"uefi_version_current,omitempty"`
	// uefi_version_virtio_blk_current is the currently installed UEFI
	// VirtIO block driver version.
	UefiVersionVirtioBlkCurrent string `protobuf:"bytes,9,opt,name=uefi_version_virtio_blk_current,json=uefiVersionVirtioBlkCurrent,proto3" json:"uefi_version_virtio_blk_current,omitempty"`
	// uefi_version_virtio_net_current is the currently installed UEFI
	// VirtIO network driver version.
	UefiVersionVirtioNetCurrent string `protobuf:"bytes,10,opt,name=uefi_version_virtio_net_current,json=uefiVersionVirtioNetCurrent,proto3" json:"uefi_version_virtio_net_current,omitempty"`
	// base_mac is the base MAC address for the device as a string.
	BaseMac string `protobuf:"bytes,11,opt,name=base_mac,json=baseMac,proto3" json:"base_mac,omitempty"`
	// status is the status string returned by mlxfwmanager.
	Status        string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlxDeviceInfo) Reset() {
	*x = MlxDeviceInfo{}
	mi := &file_mlx_device_carbide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlxDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlxDeviceInfo) ProtoMessage() {}

func (x *MlxDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlxDeviceInfo.ProtoReflect.Descriptor instead.
func (*MlxDeviceInfo) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{1}
}

func (x *MlxDeviceInfo) GetPciName() string {
	if x != nil {
		return x.PciName
	}
	return ""
}

func (x *MlxDeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *MlxDeviceInfo) GetPsid() string {
	if x != nil {
		return x.Psid
	}
	return ""
}

func (x *MlxDeviceInfo) GetDeviceDescription() string {
	if x != nil {
		return x.DeviceDescription
	}
	return ""
}

func (x *MlxDeviceInfo) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *MlxDeviceInfo) GetFwVersionCurrent() string {
	if x != nil {
		return x.FwVersionCurrent
	}
	return ""
}

func (x *MlxDeviceInfo) GetPxeVersionCurrent() string {
	if x != nil {
		return x.PxeVersionCurrent
	}
	return ""
}

func (x *MlxDeviceInfo) GetUefiVersionCurrent() string {
	if x != nil {
		return x.UefiVersionCurrent
	}
	return ""
}

func (x *MlxDeviceInfo) GetUefiVersionVirtioBlkCurrent() string {
	if x != nil {
		return x.UefiVersionVirtioBlkCurrent
	}
	return ""
}

func (x *MlxDeviceInfo) GetUefiVersionVirtioNetCurrent() string {
	if x != nil {
		return x.UefiVersionVirtioNetCurrent
	}
	return ""
}

func (x *MlxDeviceInfo) GetBaseMac() string {
	if x != nil {
		return x.BaseMac
	}
	return ""
}

func (x *MlxDeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DeviceFilterSet represents a collection of filters that must all match.
type DeviceFilterSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filters contains the list of individual filters to apply.
	Filters       []*DeviceFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFilterSet) Reset() {
	*x = DeviceFilterSet{}
	mi := &file_mlx_device_carbide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFilterSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFilterSet) ProtoMessage() {}

func (x *DeviceFilterSet) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFilterSet.ProtoReflect.Descriptor instead.
func (*DeviceFilterSet) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceFilterSet) GetFilters() []*DeviceFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// DeviceFilter represents a single filter criterion for device matching.
type DeviceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field specifies which device field to match against.
	Field DeviceField `protobuf:"varint,1,opt,name=field,proto3,enum=mlx_device.DeviceField" json:"field,omitempty"`
	// values contains the list of acceptable values for this field.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// match_mode defines how values should be matched against the device field.
	MatchMode     MatchMode `protobuf:"varint,3,opt,name=match_mode,json=matchMode,proto3,enum=mlx_device.MatchMode" json:"match_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFilter) Reset() {
	*x = DeviceFilter{}
	mi := &file_mlx_device_carbide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFilter) ProtoMessage() {}

func (x *DeviceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFilter.ProtoReflect.Descriptor instead.
func (*DeviceFilter) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceFilter) GetField() DeviceField {
	if x != nil {
		return x.Field
	}
	return DeviceField_DEVICE_FIELD_UNSPECIFIED
}

func (x *DeviceFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DeviceFilter) GetMatchMode() MatchMode {
	if x != nil {
		return x.MatchMode
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

// ProfileTargetConstraints defines criteria for matching devices
// to configuration profiles.
type ProfileTargetConstraints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_types contains allowed device type prefixes for matching.
	DeviceTypes []string `protobuf:"bytes,1,rep,name=device_types,json=deviceTypes,proto3" json:"device_types,omitempty"`
	// part_numbers contains allowed part number prefixes for matching.
	PartNumbers []string `protobuf:"bytes,2,rep,name=part_numbers,json=partNumbers,proto3" json:"part_numbers,omitempty"`
	// fw_versions contains allowed firmware version prefixes for matching.
	FwVersions    []string `protobuf:"bytes,3,rep,name=fw_versions,json=fwVersions,proto3" json:"fw_versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileTargetConstraints) Reset() {
	*x = ProfileTargetConstraints{}
	mi := &file_mlx_device_carbide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileTargetConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileTargetConstraints) ProtoMessage() {}

func (x *ProfileTargetConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileTargetConstraints.ProtoReflect.Descriptor instead.
func (*ProfileTargetConstraints) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileTargetConstraints) GetDeviceTypes() []string {
	if x != nil {
		return x.DeviceTypes
	}
	return nil
}

func (x *ProfileTargetConstraints) GetPartNumbers() []string {
	if x != nil {
		return x.PartNumbers
	}
	return nil
}

func (x *ProfileTargetConstraints) GetFwVersions() []string {
	if x != nil {
		return x.FwVersions
	}
	return nil
}

// PublishMlxDeviceReportRequest is sent by scout or the agent
// into carbide-api so that we can both observe the current
// state of the Mellanox devices (DPAs and DPUs), and potentially
// decide to take action on them (instruct scout to update
// firmware, configuration, etc).
type PublishMlxDeviceReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *MlxDeviceReport       `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMlxDeviceReportRequest) Reset() {
	*x = PublishMlxDeviceReportRequest{}
	mi := &file_mlx_device_carbide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMlxDeviceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMlxDeviceReportRequest) ProtoMessage() {}

func (x *PublishMlxDeviceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMlxDeviceReportRequest.ProtoReflect.Descriptor instead.
func (*PublishMlxDeviceReportRequest) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{5}
}

func (x *PublishMlxDeviceReportRequest) GetReport() *MlxDeviceReport {
	if x != nil {
		return x.Report
	}
	return nil
}

// PublishMlxDeviceReportResponse is returned by carbide-api
// in response to a PublishMlxDeviceReportRequest. It currently
// is actually just a placeholder response, but there's a good
// chance it will soon contain actions to take based on the
// observations made in the parent request.
type PublishMlxDeviceReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMlxDeviceReportResponse) Reset() {
	*x = PublishMlxDeviceReportResponse{}
	mi := &file_mlx_device_carbide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMlxDeviceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMlxDeviceReportResponse) ProtoMessage() {}

func (x *PublishMlxDeviceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMlxDeviceReportResponse.ProtoReflect.Descriptor instead.
func (*PublishMlxDeviceReportResponse) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{6}
}

// SerializableMlxConfigProfile is a protobuf representation
// of an mlxconfig-profile SerializableProfile, which itself
// is a serializable representation of an MlxConfigProfile.
// This is used for sending down a profile configuration from
// the API to scout (or the agent) for applying mlxconfig
// based configuration to a device. The profile itself can
// be defined as TOML in the carbide-api config, or it
// can be stored in the database. The profiles themselves
// are ultimately deserialized to MlxConfigProfile instances
// within their respective components, but we then convert
// to a SerializableProfile before serializing to/from
// a TOML/YAML/JSON/protobuf format.
type SerializableMlxConfigProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the profile name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// registry_name is the mlx variable configuration
	// registry that this profile is backed by. The registry
	// is where variable types are assigned, as well as
	// any device filters for what device types are allowed
	// to be used.
	RegistryName string `protobuf:"bytes,2,opt,name=registry_name,json=registryName,proto3" json:"registry_name,omitempty"`
	// description is an optional description for the profile.
	// It should probably generally be set, but whatever I made
	// it optional.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// config is a map of variable -> value, where, in this case,
	// the value is actually a YAML string representation of
	// the underlying value (which is how we're serializing it
	// out to send it over the wire). If for some reason someone
	// tries fuddling with direct proto values, then it will
	// just fail to deserialize to a SerializableProfile on
	// the other side (since we attempt to deserialize to the
	// underlying variable-typed value). I could have also done
	// something fancy with a map<string, special-oneof-type> to
	// be able to [de]serialize with typed values, but it seemed
	// like a lot of extra work for something that is pretty well
	// wrapped and bounded by typing already.
	Config        map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializableMlxConfigProfile) Reset() {
	*x = SerializableMlxConfigProfile{}
	mi := &file_mlx_device_carbide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializableMlxConfigProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializableMlxConfigProfile) ProtoMessage() {}

func (x *SerializableMlxConfigProfile) ProtoReflect() protoreflect.Message {
	mi := &file_mlx_device_carbide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializableMlxConfigProfile.ProtoReflect.Descriptor instead.
func (*SerializableMlxConfigProfile) Descriptor() ([]byte, []int) {
	return file_mlx_device_carbide_proto_rawDescGZIP(), []int{7}
}

func (x *SerializableMlxConfigProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerializableMlxConfigProfile) GetRegistryName() string {
	if x != nil {
		return x.RegistryName
	}
	return ""
}

func (x *SerializableMlxConfigProfile) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SerializableMlxConfigProfile) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_mlx_device_carbide_proto protoreflect.FileDescriptor

const file_mlx_device_carbide_proto_rawDesc = "" +
	"\n" +
	"\x18mlx_device_carbide.proto\x12\n" +
	"mlx_device\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\x0fMlxDeviceReport\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\adevices\x18\x03 \x03(\v2\x19.mlx_device.MlxDeviceInfoR\adevices\x12:\n" +
	"\afilters\x18\x04 \x01(\v2\x1b.mlx_device.DeviceFilterSetH\x00R\afilters\x88\x01\x01B\n" +
	"\n" +
	"\b_filters\"\xfe\x03\n" +
	"\rMlxDeviceInfo\x12\x19\n" +
	"\bpci_name\x18\x01 \x01(\tR\apciName\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\x12\x12\n" +
	"\x04psid\x18\x03 \x01(\tR\x04psid\x12-\n" +
	"\x12device_description\x18\x04 \x01(\tR\x11deviceDescription\x12\x1f\n" +
	"\vpart_number\x18\x05 \x01(\tR\n" +
	"partNumber\x12,\n" +
	"\x12fw_version_current\x18\x06 \x01(\tR\x10fwVersionCurrent\x12.\n" +
	"\x13pxe_version_current\x18\a \x01(\tR\x11pxeVersionCurrent\x120\n" +
	"\x14uefi_version_current\x18\b \x01(\tR\x12uefiVersionCurrent\x12D\n" +
	"\x1fuefi_version_virtio_blk_current\x18\t \x01(\tR\x1buefiVersionVirtioBlkCurrent\x12D\n" +
	"\x1fuefi_version_virtio_net_current\x18\n" +
	" \x01(\tR\x1buefiVersionVirtioNetCurrent\x12\x19\n" +
	"\bbase_mac\x18\v \x01(\tR\abaseMac\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"E\n" +
	"\x0fDeviceFilterSet\x122\n" +
	"\afilters\x18\x01 \x03(\v2\x18.mlx_device.DeviceFilterR\afilters\"\x8b\x01\n" +
	"\fDeviceFilter\x12-\n" +
	"\x05field\x18\x01 \x01(\x0e2\x17.mlx_device.DeviceFieldR\x05field\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x124\n" +
	"\n" +
	"match_mode\x18\x03 \x01(\x0e2\x15.mlx_device.MatchModeR\tmatchMode\"\x81\x01\n" +
	"\x18ProfileTargetConstraints\x12!\n" +
	"\fdevice_types\x18\x01 \x03(\tR\vdeviceTypes\x12!\n" +
	"\fpart_numbers\x18\x02 \x03(\tR\vpartNumbers\x12\x1f\n" +
	"\vfw_versions\x18\x03 \x03(\tR\n" +
	"fwVersions\"T\n" +
	"\x1dPublishMlxDeviceReportRequest\x123\n" +
	"\x06report\x18\x01 \x01(\v2\x1b.mlx_device.MlxDeviceReportR\x06report\" \n" +
	"\x1ePublishMlxDeviceReportResponse\"\x97\x02\n" +
	"\x1cSerializableMlxConfigProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rregistry_name\x18\x02 \x01(\tR\fregistryName\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12L\n" +
	"\x06config\x18\x04 \x03(\v24.mlx_device.SerializableMlxConfigProfile.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description*\xfa\x01\n" +
	"\vDeviceField\x12\x1c\n" +
	"\x18DEVICE_FIELD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DEVICE_FIELD_DEVICE_TYPE\x10\x01\x12\x1c\n" +
	"\x18DEVICE_FIELD_PART_NUMBER\x10\x02\x12!\n" +
	"\x1dDEVICE_FIELD_FIRMWARE_VERSION\x10\x03\x12\x1c\n" +
	"\x18DEVICE_FIELD_MAC_ADDRESS\x10\x04\x12\x1c\n" +
	"\x18DEVICE_FIELD_DESCRIPTION\x10\x05\x12\x19\n" +
	"\x15DEVICE_FIELD_PCI_NAME\x10\x06\x12\x17\n" +
	"\x13DEVICE_FIELD_STATUS\x10\a*j\n" +
	"\tMatchMode\x12\x1a\n" +
	"\x16MATCH_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MATCH_MODE_REGEX\x10\x01\x12\x14\n" +
	"\x10MATCH_MODE_EXACT\x10\x02\x12\x15\n" +
	"\x11MATCH_MODE_PREFIX\x10\x03BCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_mlx_device_carbide_proto_rawDescOnce sync.Once
	file_mlx_device_carbide_proto_rawDescData []byte
)

func file_mlx_device_carbide_proto_rawDescGZIP() []byte {
	file_mlx_device_carbide_proto_rawDescOnce.Do(func() {
		file_mlx_device_carbide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mlx_device_carbide_proto_rawDesc), len(file_mlx_device_carbide_proto_rawDesc)))
	})
	return file_mlx_device_carbide_proto_rawDescData
}

var file_mlx_device_carbide_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mlx_device_carbide_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mlx_device_carbide_proto_goTypes = []any{
	(DeviceField)(0),                       // 0: mlx_device.DeviceField
	(MatchMode)(0),                         // 1: mlx_device.MatchMode
	(*MlxDeviceReport)(nil),                // 2: mlx_device.MlxDeviceReport
	(*MlxDeviceInfo)(nil),                  // 3: mlx_device.MlxDeviceInfo
	(*DeviceFilterSet)(nil),                // 4: mlx_device.DeviceFilterSet
	(*DeviceFilter)(nil),                   // 5: mlx_device.DeviceFilter
	(*ProfileTargetConstraints)(nil),       // 6: mlx_device.ProfileTargetConstraints
	(*PublishMlxDeviceReportRequest)(nil),  // 7: mlx_device.PublishMlxDeviceReportRequest
	(*PublishMlxDeviceReportResponse)(nil), // 8: mlx_device.PublishMlxDeviceReportResponse
	(*SerializableMlxConfigProfile)(nil),   // 9: mlx_device.SerializableMlxConfigProfile
	nil,                                    // 10: mlx_device.SerializableMlxConfigProfile.ConfigEntry
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_mlx_device_carbide_proto_depIdxs = []int32{
	11, // 0: mlx_device.MlxDeviceReport.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: mlx_device.MlxDeviceReport.devices:type_name -> mlx_device.MlxDeviceInfo
	4,  // 2: mlx_device.MlxDeviceReport.filters:type_name -> mlx_device.DeviceFilterSet
	5,  // 3: mlx_device.DeviceFilterSet.filters:type_name -> mlx_device.DeviceFilter
	0,  // 4: mlx_device.DeviceFilter.field:type_name -> mlx_device.DeviceField
	1,  // 5: mlx_device.DeviceFilter.match_mode:type_name -> mlx_device.MatchMode
	2,  // 6: mlx_device.PublishMlxDeviceReportRequest.report:type_name -> mlx_device.MlxDeviceReport
	10, // 7: mlx_device.SerializableMlxConfigProfile.config:type_name -> mlx_device.SerializableMlxConfigProfile.ConfigEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mlx_device_carbide_proto_init() }
func file_mlx_device_carbide_proto_init() {
	if File_mlx_device_carbide_proto != nil {
		return
	}
	file_mlx_device_carbide_proto_msgTypes[0].OneofWrappers = []any{}
	file_mlx_device_carbide_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mlx_device_carbide_proto_rawDesc), len(file_mlx_device_carbide_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mlx_device_carbide_proto_goTypes,
		DependencyIndexes: file_mlx_device_carbide_proto_depIdxs,
		EnumInfos:         file_mlx_device_carbide_proto_enumTypes,
		MessageInfos:      file_mlx_device_carbide_proto_msgTypes,
	}.Build()
	File_mlx_device_carbide_proto = out.File
	file_mlx_device_carbide_proto_goTypes = nil
	file_mlx_device_carbide_proto_depIdxs = nil
}
