// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sshkeygroup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSSHKeyGroupRequest - request parameters of SSHKeyGroup creation
type CreateSSHKeyGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the tenant org attached to this keyset
	TenantOrganizationId string `protobuf:"bytes,1,opt,name=tenant_organization_id,json=tenantOrganizationId,proto3" json:"tenant_organization_id,omitempty"`
	// the id of the key, provided by the tenant.  Must be unique within the
	// tenant's organization.
	KeysetId string `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	// version of the keyset
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// list of public keys associated with the tenant org
	PublicKeys    []*TenantPublicKey `protobuf:"bytes,4,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Options       *WorkflowOptions   `protobuf:"bytes,5,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSSHKeyGroupRequest) Reset() {
	*x = CreateSSHKeyGroupRequest{}
	mi := &file_sshkeygroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSSHKeyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSSHKeyGroupRequest) ProtoMessage() {}

func (x *CreateSSHKeyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSSHKeyGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateSSHKeyGroupRequest) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSSHKeyGroupRequest) GetTenantOrganizationId() string {
	if x != nil {
		return x.TenantOrganizationId
	}
	return ""
}

func (x *CreateSSHKeyGroupRequest) GetKeysetId() string {
	if x != nil {
		return x.KeysetId
	}
	return ""
}

func (x *CreateSSHKeyGroupRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateSSHKeyGroupRequest) GetPublicKeys() []*TenantPublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *CreateSSHKeyGroupRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// UpdateSSHKeyGroupRequest - request parameters to update SSHKeyGroup
type UpdateSSHKeyGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the tenant org attached to this keyset
	TenantOrganizationId string `protobuf:"bytes,1,opt,name=tenant_organization_id,json=tenantOrganizationId,proto3" json:"tenant_organization_id,omitempty"`
	// the id of the key, provided by the tenant.  Must be unique within the
	// tenant's organization.
	KeysetId string `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	// version of the keyset
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// list of public keys associated with the tenant org
	PublicKeys []*TenantPublicKey `protobuf:"bytes,4,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	// optional version string to check before updating
	IfVersionMatch *string          `protobuf:"bytes,5,opt,name=if_version_match,json=ifVersionMatch,proto3,oneof" json:"if_version_match,omitempty"`
	Options        *WorkflowOptions `protobuf:"bytes,6,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSSHKeyGroupRequest) Reset() {
	*x = UpdateSSHKeyGroupRequest{}
	mi := &file_sshkeygroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSSHKeyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSSHKeyGroupRequest) ProtoMessage() {}

func (x *UpdateSSHKeyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSSHKeyGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateSSHKeyGroupRequest) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSSHKeyGroupRequest) GetTenantOrganizationId() string {
	if x != nil {
		return x.TenantOrganizationId
	}
	return ""
}

func (x *UpdateSSHKeyGroupRequest) GetKeysetId() string {
	if x != nil {
		return x.KeysetId
	}
	return ""
}

func (x *UpdateSSHKeyGroupRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateSSHKeyGroupRequest) GetPublicKeys() []*TenantPublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *UpdateSSHKeyGroupRequest) GetIfVersionMatch() string {
	if x != nil && x.IfVersionMatch != nil {
		return *x.IfVersionMatch
	}
	return ""
}

func (x *UpdateSSHKeyGroupRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// DeleteSSHKeyGroupRequest - request parameters to delete SSHKeyGroup
type DeleteSSHKeyGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the tenant org attached to this keyset
	TenantOrganizationId string `protobuf:"bytes,1,opt,name=tenant_organization_id,json=tenantOrganizationId,proto3" json:"tenant_organization_id,omitempty"`
	// the id of the key, provided by the tenant.  Must be unique within the
	// tenant's organization.
	KeysetId      string           `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	Options       *WorkflowOptions `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSSHKeyGroupRequest) Reset() {
	*x = DeleteSSHKeyGroupRequest{}
	mi := &file_sshkeygroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSSHKeyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSSHKeyGroupRequest) ProtoMessage() {}

func (x *DeleteSSHKeyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSSHKeyGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteSSHKeyGroupRequest) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSSHKeyGroupRequest) GetTenantOrganizationId() string {
	if x != nil {
		return x.TenantOrganizationId
	}
	return ""
}

func (x *DeleteSSHKeyGroupRequest) GetKeysetId() string {
	if x != nil {
		return x.KeysetId
	}
	return ""
}

func (x *DeleteSSHKeyGroupRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetSSHKeyGroup - request to get an SSHKeyGroup
// ListSSHKeyGroup - request to list the existing SSHKeyGroup
type GetSSHKeyGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the tenant org attached to this keyset
	TenantOrganizationId string `protobuf:"bytes,1,opt,name=tenant_organization_id,json=tenantOrganizationId,proto3" json:"tenant_organization_id,omitempty"`
	// the id of the key, provided by the tenant.  Must be unique within the
	// tenant's organization.
	KeysetId string `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	// request key data
	IncludeKeyData bool             `protobuf:"varint,3,opt,name=include_key_data,json=includeKeyData,proto3" json:"include_key_data,omitempty"`
	Options        *WorkflowOptions `protobuf:"bytes,4,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSSHKeyGroup) Reset() {
	*x = GetSSHKeyGroup{}
	mi := &file_sshkeygroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSSHKeyGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSHKeyGroup) ProtoMessage() {}

func (x *GetSSHKeyGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSHKeyGroup.ProtoReflect.Descriptor instead.
func (*GetSSHKeyGroup) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{3}
}

func (x *GetSSHKeyGroup) GetTenantOrganizationId() string {
	if x != nil {
		return x.TenantOrganizationId
	}
	return ""
}

func (x *GetSSHKeyGroup) GetKeysetId() string {
	if x != nil {
		return x.KeysetId
	}
	return ""
}

func (x *GetSSHKeyGroup) GetIncludeKeyData() bool {
	if x != nil {
		return x.IncludeKeyData
	}
	return false
}

func (x *GetSSHKeyGroup) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SSHKeyGroupInfo - response for SSHKeyGroup create/update/delete request
type SSHKeyGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	ObjectStatus  ObjectStatus           `protobuf:"varint,2,opt,name=object_status,json=objectStatus,proto3,enum=workflows.v1.ObjectStatus" json:"object_status,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	TenantKeyset  *TenantKeyset          `protobuf:"bytes,4,opt,name=tenant_keyset,json=tenantKeyset,proto3" json:"tenant_keyset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeyGroupInfo) Reset() {
	*x = SSHKeyGroupInfo{}
	mi := &file_sshkeygroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeyGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeyGroupInfo) ProtoMessage() {}

func (x *SSHKeyGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKeyGroupInfo.ProtoReflect.Descriptor instead.
func (*SSHKeyGroupInfo) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{4}
}

func (x *SSHKeyGroupInfo) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *SSHKeyGroupInfo) GetObjectStatus() ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return ObjectStatus_OBJECT_STATUS_UNSPECIFIED
}

func (x *SSHKeyGroupInfo) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *SSHKeyGroupInfo) GetTenantKeyset() *TenantKeyset {
	if x != nil {
		return x.TenantKeyset
	}
	return nil
}

// GetSSHKeyGroupResponse - response for SSHKeyGroup Get queries
type GetSSHKeyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	List          *TenantKeySetList      `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	TransactionId *TransactionID         `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSSHKeyGroupResponse) Reset() {
	*x = GetSSHKeyGroupResponse{}
	mi := &file_sshkeygroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSSHKeyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSHKeyGroupResponse) ProtoMessage() {}

func (x *GetSSHKeyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSHKeyGroupResponse.ProtoReflect.Descriptor instead.
func (*GetSSHKeyGroupResponse) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{5}
}

func (x *GetSSHKeyGroupResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *GetSSHKeyGroupResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetSSHKeyGroupResponse) GetList() *TenantKeySetList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetSSHKeyGroupResponse) GetTransactionId() *TransactionID {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

// SSHKeyGroupInventory - inventory info of all SSHKeyGroups on Site collected
// periodically
type SSHKeyGroupInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of SSH keysets
	TenantKeysets []*TenantKeyset `protobuf:"bytes,1,rep,name=tenant_keysets,json=tenantKeysets,proto3" json:"tenant_keysets,omitempty"`
	// Reported timestamp of SSH keyset inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,3,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	StatusMsg       string          `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeyGroupInventory) Reset() {
	*x = SSHKeyGroupInventory{}
	mi := &file_sshkeygroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeyGroupInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeyGroupInventory) ProtoMessage() {}

func (x *SSHKeyGroupInventory) ProtoReflect() protoreflect.Message {
	mi := &file_sshkeygroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKeyGroupInventory.ProtoReflect.Descriptor instead.
func (*SSHKeyGroupInventory) Descriptor() ([]byte, []int) {
	return file_sshkeygroup_proto_rawDescGZIP(), []int{6}
}

func (x *SSHKeyGroupInventory) GetTenantKeysets() []*TenantKeyset {
	if x != nil {
		return x.TenantKeysets
	}
	return nil
}

func (x *SSHKeyGroupInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SSHKeyGroupInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *SSHKeyGroupInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *SSHKeyGroupInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_sshkeygroup_proto protoreflect.FileDescriptor

const file_sshkeygroup_proto_rawDesc = "" +
	"\n" +
	"\x11sshkeygroup.proto\x12\fworkflows.v1\x1a\x0eworkflow.proto\x1a\x13forge_carbide.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x18CreateSSHKeyGroupRequest\x124\n" +
	"\x16tenant_organization_id\x18\x01 \x01(\tR\x14tenantOrganizationId\x12\x1b\n" +
	"\tkeyset_id\x18\x02 \x01(\tR\bkeysetId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x127\n" +
	"\vpublic_keys\x18\x04 \x03(\v2\x16.forge.TenantPublicKeyR\n" +
	"publicKeys\x12<\n" +
	"\aoptions\x18\x05 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xce\x02\n" +
	"\x18UpdateSSHKeyGroupRequest\x124\n" +
	"\x16tenant_organization_id\x18\x01 \x01(\tR\x14tenantOrganizationId\x12\x1b\n" +
	"\tkeyset_id\x18\x02 \x01(\tR\bkeysetId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x127\n" +
	"\vpublic_keys\x18\x04 \x03(\v2\x16.forge.TenantPublicKeyR\n" +
	"publicKeys\x12-\n" +
	"\x10if_version_match\x18\x05 \x01(\tH\x00R\x0eifVersionMatch\x88\x01\x01\x12<\n" +
	"\aoptions\x18\x06 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x01R\aoptions\x88\x01\x01B\x13\n" +
	"\x11_if_version_matchB\n" +
	"\n" +
	"\b_options\"\xb7\x01\n" +
	"\x18DeleteSSHKeyGroupRequest\x124\n" +
	"\x16tenant_organization_id\x18\x01 \x01(\tR\x14tenantOrganizationId\x12\x1b\n" +
	"\tkeyset_id\x18\x02 \x01(\tR\bkeysetId\x12<\n" +
	"\aoptions\x18\x03 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xd7\x01\n" +
	"\x0eGetSSHKeyGroup\x124\n" +
	"\x16tenant_organization_id\x18\x01 \x01(\tR\x14tenantOrganizationId\x12\x1b\n" +
	"\tkeyset_id\x18\x02 \x01(\tR\bkeysetId\x12(\n" +
	"\x10include_key_data\x18\x03 \x01(\bR\x0eincludeKeyData\x12<\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xe1\x01\n" +
	"\x0fSSHKeyGroupInfo\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12?\n" +
	"\robject_status\x18\x02 \x01(\x0e2\x1a.workflows.v1.ObjectStatusR\fobjectStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x128\n" +
	"\rtenant_keyset\x18\x04 \x01(\v2\x13.forge.TenantKeysetR\ftenantKeyset\"\xde\x01\n" +
	"\x16GetSSHKeyGroupResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12+\n" +
	"\x04list\x18\x03 \x01(\v2\x17.forge.TenantKeySetListR\x04list\x12B\n" +
	"\x0etransaction_id\x18\x04 \x01(\v2\x1b.workflows.v1.TransactionIDR\rtransactionId\"\xb9\x02\n" +
	"\x14SSHKeyGroupInventory\x12:\n" +
	"\x0etenant_keysets\x18\x01 \x03(\v2\x13.forge.TenantKeysetR\rtenantKeysets\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x10inventory_status\x18\x03 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_sshkeygroup_proto_rawDescOnce sync.Once
	file_sshkeygroup_proto_rawDescData []byte
)

func file_sshkeygroup_proto_rawDescGZIP() []byte {
	file_sshkeygroup_proto_rawDescOnce.Do(func() {
		file_sshkeygroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sshkeygroup_proto_rawDesc), len(file_sshkeygroup_proto_rawDesc)))
	})
	return file_sshkeygroup_proto_rawDescData
}

var file_sshkeygroup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sshkeygroup_proto_goTypes = []any{
	(*CreateSSHKeyGroupRequest)(nil), // 0: workflows.v1.CreateSSHKeyGroupRequest
	(*UpdateSSHKeyGroupRequest)(nil), // 1: workflows.v1.UpdateSSHKeyGroupRequest
	(*DeleteSSHKeyGroupRequest)(nil), // 2: workflows.v1.DeleteSSHKeyGroupRequest
	(*GetSSHKeyGroup)(nil),           // 3: workflows.v1.GetSSHKeyGroup
	(*SSHKeyGroupInfo)(nil),          // 4: workflows.v1.SSHKeyGroupInfo
	(*GetSSHKeyGroupResponse)(nil),   // 5: workflows.v1.GetSSHKeyGroupResponse
	(*SSHKeyGroupInventory)(nil),     // 6: workflows.v1.SSHKeyGroupInventory
	(*TenantPublicKey)(nil),          // 7: forge.TenantPublicKey
	(*WorkflowOptions)(nil),          // 8: workflows.v1.WorkflowOptions
	(WorkflowStatus)(0),              // 9: workflows.v1.WorkflowStatus
	(ObjectStatus)(0),                // 10: workflows.v1.ObjectStatus
	(*TenantKeyset)(nil),             // 11: forge.TenantKeyset
	(*TenantKeySetList)(nil),         // 12: forge.TenantKeySetList
	(*TransactionID)(nil),            // 13: workflows.v1.TransactionID
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(InventoryStatus)(0),             // 15: workflows.v1.InventoryStatus
	(*InventoryPage)(nil),            // 16: workflows.v1.InventoryPage
}
var file_sshkeygroup_proto_depIdxs = []int32{
	7,  // 0: workflows.v1.CreateSSHKeyGroupRequest.public_keys:type_name -> forge.TenantPublicKey
	8,  // 1: workflows.v1.CreateSSHKeyGroupRequest.options:type_name -> workflows.v1.WorkflowOptions
	7,  // 2: workflows.v1.UpdateSSHKeyGroupRequest.public_keys:type_name -> forge.TenantPublicKey
	8,  // 3: workflows.v1.UpdateSSHKeyGroupRequest.options:type_name -> workflows.v1.WorkflowOptions
	8,  // 4: workflows.v1.DeleteSSHKeyGroupRequest.options:type_name -> workflows.v1.WorkflowOptions
	8,  // 5: workflows.v1.GetSSHKeyGroup.options:type_name -> workflows.v1.WorkflowOptions
	9,  // 6: workflows.v1.SSHKeyGroupInfo.status:type_name -> workflows.v1.WorkflowStatus
	10, // 7: workflows.v1.SSHKeyGroupInfo.object_status:type_name -> workflows.v1.ObjectStatus
	11, // 8: workflows.v1.SSHKeyGroupInfo.tenant_keyset:type_name -> forge.TenantKeyset
	9,  // 9: workflows.v1.GetSSHKeyGroupResponse.status:type_name -> workflows.v1.WorkflowStatus
	12, // 10: workflows.v1.GetSSHKeyGroupResponse.list:type_name -> forge.TenantKeySetList
	13, // 11: workflows.v1.GetSSHKeyGroupResponse.transaction_id:type_name -> workflows.v1.TransactionID
	11, // 12: workflows.v1.SSHKeyGroupInventory.tenant_keysets:type_name -> forge.TenantKeyset
	14, // 13: workflows.v1.SSHKeyGroupInventory.timestamp:type_name -> google.protobuf.Timestamp
	15, // 14: workflows.v1.SSHKeyGroupInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	16, // 15: workflows.v1.SSHKeyGroupInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_sshkeygroup_proto_init() }
func file_sshkeygroup_proto_init() {
	if File_sshkeygroup_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_forge_carbide_proto_init()
	file_sshkeygroup_proto_msgTypes[0].OneofWrappers = []any{}
	file_sshkeygroup_proto_msgTypes[1].OneofWrappers = []any{}
	file_sshkeygroup_proto_msgTypes[2].OneofWrappers = []any{}
	file_sshkeygroup_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sshkeygroup_proto_rawDesc), len(file_sshkeygroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sshkeygroup_proto_goTypes,
		DependencyIndexes: file_sshkeygroup_proto_depIdxs,
		MessageInfos:      file_sshkeygroup_proto_msgTypes,
	}.Build()
	File_sshkeygroup_proto = out.File
	file_sshkeygroup_proto_goTypes = nil
	file_sshkeygroup_proto_depIdxs = nil
}
