// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: subnet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubnetInfo - response for subnet create request
type SubnetInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=workflows.v1.WorkflowStatus" json:"status,omitempty"`
	ObjectStatus   ObjectStatus           `protobuf:"varint,2,opt,name=object_status,json=objectStatus,proto3,enum=workflows.v1.ObjectStatus" json:"object_status,omitempty"`
	StatusMsg      string                 `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	NetworkSegment *NetworkSegment        `protobuf:"bytes,4,opt,name=network_segment,json=networkSegment,proto3" json:"network_segment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubnetInfo) Reset() {
	*x = SubnetInfo{}
	mi := &file_subnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetInfo) ProtoMessage() {}

func (x *SubnetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetInfo.ProtoReflect.Descriptor instead.
func (*SubnetInfo) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{0}
}

func (x *SubnetInfo) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *SubnetInfo) GetObjectStatus() ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return ObjectStatus_OBJECT_STATUS_UNSPECIFIED
}

func (x *SubnetInfo) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *SubnetInfo) GetNetworkSegment() *NetworkSegment {
	if x != nil {
		return x.NetworkSegment
	}
	return nil
}

// NetworkPrefixInfo - request parameters of network prefix
type NetworkPrefixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Gateway       *string                `protobuf:"bytes,2,opt,name=gateway,proto3,oneof" json:"gateway,omitempty"`
	ReserveFirst  int32                  `protobuf:"varint,3,opt,name=reserve_first,json=reserveFirst,proto3" json:"reserve_first,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPrefixInfo) Reset() {
	*x = NetworkPrefixInfo{}
	mi := &file_subnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPrefixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPrefixInfo) ProtoMessage() {}

func (x *NetworkPrefixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPrefixInfo.ProtoReflect.Descriptor instead.
func (*NetworkPrefixInfo) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkPrefixInfo) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *NetworkPrefixInfo) GetGateway() string {
	if x != nil && x.Gateway != nil {
		return *x.Gateway
	}
	return ""
}

func (x *NetworkPrefixInfo) GetReserveFirst() int32 {
	if x != nil {
		return x.ReserveFirst
	}
	return 0
}

// CreateSubnetRequest - request parameters of subnet creation
type CreateSubnetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VpcId           *UUID                  `protobuf:"bytes,2,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubdomainId     *UUID                  `protobuf:"bytes,3,opt,name=subdomain_id,json=subdomainId,proto3,oneof" json:"subdomain_id,omitempty"`
	Mtu             *int32                 `protobuf:"varint,4,opt,name=mtu,proto3,oneof" json:"mtu,omitempty"`
	NetworkPrefixes []*NetworkPrefixInfo   `protobuf:"bytes,5,rep,name=network_prefixes,json=networkPrefixes,proto3" json:"network_prefixes,omitempty"`
	// Workflow Options
	Options *WorkflowOptions `protobuf:"bytes,6,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// ID of the subnet
	SubnetId      *UUID `protobuf:"bytes,7,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubnetRequest) Reset() {
	*x = CreateSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubnetRequest) ProtoMessage() {}

func (x *CreateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubnetRequest.ProtoReflect.Descriptor instead.
func (*CreateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubnetRequest) GetVpcId() *UUID {
	if x != nil {
		return x.VpcId
	}
	return nil
}

func (x *CreateSubnetRequest) GetSubdomainId() *UUID {
	if x != nil {
		return x.SubdomainId
	}
	return nil
}

func (x *CreateSubnetRequest) GetMtu() int32 {
	if x != nil && x.Mtu != nil {
		return *x.Mtu
	}
	return 0
}

func (x *CreateSubnetRequest) GetNetworkPrefixes() []*NetworkPrefixInfo {
	if x != nil {
		return x.NetworkPrefixes
	}
	return nil
}

func (x *CreateSubnetRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateSubnetRequest) GetSubnetId() *UUID {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

// DeleteSubnetRequest - request parameters of subnet deletion
type DeleteSubnetRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NetworkSegmentId *UUID                  `protobuf:"bytes,1,opt,name=network_segment_id,json=networkSegmentId,proto3" json:"network_segment_id,omitempty"`
	// Workflow Options
	Options       *WorkflowOptions `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubnetRequest) Reset() {
	*x = DeleteSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubnetRequest) ProtoMessage() {}

func (x *DeleteSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubnetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSubnetRequest) GetNetworkSegmentId() *UUID {
	if x != nil {
		return x.NetworkSegmentId
	}
	return nil
}

func (x *DeleteSubnetRequest) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SubnetInventory - inventory info of all Subnets (Network Segments)
// periodically collected
type SubnetInventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Network Segments
	Segments []*NetworkSegment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Reported timestamp of Segment inventory
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of Inventory
	InventoryStatus InventoryStatus `protobuf:"varint,3,opt,name=inventory_status,json=inventoryStatus,proto3,enum=workflows.v1.InventoryStatus" json:"inventory_status,omitempty"`
	StatusMsg       string          `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Inventory page information
	InventoryPage *InventoryPage `protobuf:"bytes,5,opt,name=inventory_page,json=inventoryPage,proto3" json:"inventory_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetInventory) Reset() {
	*x = SubnetInventory{}
	mi := &file_subnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetInventory) ProtoMessage() {}

func (x *SubnetInventory) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetInventory.ProtoReflect.Descriptor instead.
func (*SubnetInventory) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{4}
}

func (x *SubnetInventory) GetSegments() []*NetworkSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SubnetInventory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SubnetInventory) GetInventoryStatus() InventoryStatus {
	if x != nil {
		return x.InventoryStatus
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

func (x *SubnetInventory) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *SubnetInventory) GetInventoryPage() *InventoryPage {
	if x != nil {
		return x.InventoryPage
	}
	return nil
}

var File_subnet_proto protoreflect.FileDescriptor

const file_subnet_proto_rawDesc = "" +
	"\n" +
	"\fsubnet.proto\x12\fworkflows.v1\x1a\x0eworkflow.proto\x1a\x14common_carbide.proto\x1a\x13forge_carbide.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\n" +
	"SubnetInfo\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.workflows.v1.WorkflowStatusR\x06status\x12?\n" +
	"\robject_status\x18\x02 \x01(\x0e2\x1a.workflows.v1.ObjectStatusR\fobjectStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x12>\n" +
	"\x0fnetwork_segment\x18\x04 \x01(\v2\x15.forge.NetworkSegmentR\x0enetworkSegment\"{\n" +
	"\x11NetworkPrefixInfo\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1d\n" +
	"\agateway\x18\x02 \x01(\tH\x00R\agateway\x88\x01\x01\x12#\n" +
	"\rreserve_first\x18\x03 \x01(\x05R\freserveFirstB\n" +
	"\n" +
	"\b_gateway\"\xf5\x02\n" +
	"\x13CreateSubnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x06vpc_id\x18\x02 \x01(\v2\f.common.UUIDR\x05vpcId\x124\n" +
	"\fsubdomain_id\x18\x03 \x01(\v2\f.common.UUIDH\x00R\vsubdomainId\x88\x01\x01\x12\x15\n" +
	"\x03mtu\x18\x04 \x01(\x05H\x01R\x03mtu\x88\x01\x01\x12J\n" +
	"\x10network_prefixes\x18\x05 \x03(\v2\x1f.workflows.v1.NetworkPrefixInfoR\x0fnetworkPrefixes\x12<\n" +
	"\aoptions\x18\x06 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x02R\aoptions\x88\x01\x01\x12)\n" +
	"\tsubnet_id\x18\a \x01(\v2\f.common.UUIDR\bsubnetIdB\x0f\n" +
	"\r_subdomain_idB\x06\n" +
	"\x04_mtuB\n" +
	"\n" +
	"\b_options\"\x9b\x01\n" +
	"\x13DeleteSubnetRequest\x12:\n" +
	"\x12network_segment_id\x18\x01 \x01(\v2\f.common.UUIDR\x10networkSegmentId\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.workflows.v1.WorkflowOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\xab\x02\n" +
	"\x0fSubnetInventory\x121\n" +
	"\bsegments\x18\x01 \x03(\v2\x15.forge.NetworkSegmentR\bsegments\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x10inventory_status\x18\x03 \x01(\x0e2\x1d.workflows.v1.InventoryStatusR\x0finventoryStatus\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\x12B\n" +
	"\x0einventory_page\x18\x05 \x01(\v2\x1b.workflows.v1.InventoryPageR\rinventoryPageBCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_subnet_proto_rawDescOnce sync.Once
	file_subnet_proto_rawDescData []byte
)

func file_subnet_proto_rawDescGZIP() []byte {
	file_subnet_proto_rawDescOnce.Do(func() {
		file_subnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subnet_proto_rawDesc), len(file_subnet_proto_rawDesc)))
	})
	return file_subnet_proto_rawDescData
}

var file_subnet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_subnet_proto_goTypes = []any{
	(*SubnetInfo)(nil),            // 0: workflows.v1.SubnetInfo
	(*NetworkPrefixInfo)(nil),     // 1: workflows.v1.NetworkPrefixInfo
	(*CreateSubnetRequest)(nil),   // 2: workflows.v1.CreateSubnetRequest
	(*DeleteSubnetRequest)(nil),   // 3: workflows.v1.DeleteSubnetRequest
	(*SubnetInventory)(nil),       // 4: workflows.v1.SubnetInventory
	(WorkflowStatus)(0),           // 5: workflows.v1.WorkflowStatus
	(ObjectStatus)(0),             // 6: workflows.v1.ObjectStatus
	(*NetworkSegment)(nil),        // 7: forge.NetworkSegment
	(*UUID)(nil),                  // 8: common.UUID
	(*WorkflowOptions)(nil),       // 9: workflows.v1.WorkflowOptions
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(InventoryStatus)(0),          // 11: workflows.v1.InventoryStatus
	(*InventoryPage)(nil),         // 12: workflows.v1.InventoryPage
}
var file_subnet_proto_depIdxs = []int32{
	5,  // 0: workflows.v1.SubnetInfo.status:type_name -> workflows.v1.WorkflowStatus
	6,  // 1: workflows.v1.SubnetInfo.object_status:type_name -> workflows.v1.ObjectStatus
	7,  // 2: workflows.v1.SubnetInfo.network_segment:type_name -> forge.NetworkSegment
	8,  // 3: workflows.v1.CreateSubnetRequest.vpc_id:type_name -> common.UUID
	8,  // 4: workflows.v1.CreateSubnetRequest.subdomain_id:type_name -> common.UUID
	1,  // 5: workflows.v1.CreateSubnetRequest.network_prefixes:type_name -> workflows.v1.NetworkPrefixInfo
	9,  // 6: workflows.v1.CreateSubnetRequest.options:type_name -> workflows.v1.WorkflowOptions
	8,  // 7: workflows.v1.CreateSubnetRequest.subnet_id:type_name -> common.UUID
	8,  // 8: workflows.v1.DeleteSubnetRequest.network_segment_id:type_name -> common.UUID
	9,  // 9: workflows.v1.DeleteSubnetRequest.options:type_name -> workflows.v1.WorkflowOptions
	7,  // 10: workflows.v1.SubnetInventory.segments:type_name -> forge.NetworkSegment
	10, // 11: workflows.v1.SubnetInventory.timestamp:type_name -> google.protobuf.Timestamp
	11, // 12: workflows.v1.SubnetInventory.inventory_status:type_name -> workflows.v1.InventoryStatus
	12, // 13: workflows.v1.SubnetInventory.inventory_page:type_name -> workflows.v1.InventoryPage
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_subnet_proto_init() }
func file_subnet_proto_init() {
	if File_subnet_proto != nil {
		return
	}
	file_workflow_proto_init()
	file_common_carbide_proto_init()
	file_forge_carbide_proto_init()
	file_subnet_proto_msgTypes[1].OneofWrappers = []any{}
	file_subnet_proto_msgTypes[2].OneofWrappers = []any{}
	file_subnet_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subnet_proto_rawDesc), len(file_subnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subnet_proto_goTypes,
		DependencyIndexes: file_subnet_proto_depIdxs,
		MessageInfos:      file_subnet_proto_msgTypes,
	}.Build()
	File_subnet_proto = out.File
	file_subnet_proto_goTypes = nil
	file_subnet_proto_depIdxs = nil
}
