// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkflowStatus - response status
type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_CREATED     WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_IN_PROGRESS WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_REQUEUED    WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_SUCCESS     WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_FAILURE     WorkflowStatus = 5
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_CREATED",
		2: "WORKFLOW_STATUS_IN_PROGRESS",
		3: "WORKFLOW_STATUS_REQUEUED",
		4: "WORKFLOW_STATUS_SUCCESS",
		5: "WORKFLOW_STATUS_FAILURE",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_CREATED":     1,
		"WORKFLOW_STATUS_IN_PROGRESS": 2,
		"WORKFLOW_STATUS_REQUEUED":    3,
		"WORKFLOW_STATUS_SUCCESS":     4,
		"WORKFLOW_STATUS_FAILURE":     5,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

// WorkflowPolicy - policies of siteagent workflow
type WorkflowPolicy int32

const (
	WorkflowPolicy_WORKFLOW_POLICY_UNSPECIFIED       WorkflowPolicy = 0
	WorkflowPolicy_WORKFLOW_POLICY_DELETE_ON_FAILURE WorkflowPolicy = 1
	WorkflowPolicy_WORKFLOW_POLICY_ASYNC_NOTIFY      WorkflowPolicy = 2
)

// Enum value maps for WorkflowPolicy.
var (
	WorkflowPolicy_name = map[int32]string{
		0: "WORKFLOW_POLICY_UNSPECIFIED",
		1: "WORKFLOW_POLICY_DELETE_ON_FAILURE",
		2: "WORKFLOW_POLICY_ASYNC_NOTIFY",
	}
	WorkflowPolicy_value = map[string]int32{
		"WORKFLOW_POLICY_UNSPECIFIED":       0,
		"WORKFLOW_POLICY_DELETE_ON_FAILURE": 1,
		"WORKFLOW_POLICY_ASYNC_NOTIFY":      2,
	}
)

func (x WorkflowPolicy) Enum() *WorkflowPolicy {
	p := new(WorkflowPolicy)
	*p = x
	return p
}

func (x WorkflowPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[1].Descriptor()
}

func (WorkflowPolicy) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[1]
}

func (x WorkflowPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowPolicy.Descriptor instead.
func (WorkflowPolicy) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

// ObjectStatus - response status
type ObjectStatus int32

const (
	ObjectStatus_OBJECT_STATUS_UNSPECIFIED ObjectStatus = 0
	ObjectStatus_OBJECT_STATUS_CREATED     ObjectStatus = 1
	ObjectStatus_OBJECT_STATUS_IN_PROGRESS ObjectStatus = 2
	ObjectStatus_OBJECT_STATUS_DELETED     ObjectStatus = 3
	ObjectStatus_OBJECT_STATUS_UPDATED     ObjectStatus = 4
	ObjectStatus_OBJECT_STATUS_READY       ObjectStatus = 5
)

// Enum value maps for ObjectStatus.
var (
	ObjectStatus_name = map[int32]string{
		0: "OBJECT_STATUS_UNSPECIFIED",
		1: "OBJECT_STATUS_CREATED",
		2: "OBJECT_STATUS_IN_PROGRESS",
		3: "OBJECT_STATUS_DELETED",
		4: "OBJECT_STATUS_UPDATED",
		5: "OBJECT_STATUS_READY",
	}
	ObjectStatus_value = map[string]int32{
		"OBJECT_STATUS_UNSPECIFIED": 0,
		"OBJECT_STATUS_CREATED":     1,
		"OBJECT_STATUS_IN_PROGRESS": 2,
		"OBJECT_STATUS_DELETED":     3,
		"OBJECT_STATUS_UPDATED":     4,
		"OBJECT_STATUS_READY":       5,
	}
)

func (x ObjectStatus) Enum() *ObjectStatus {
	p := new(ObjectStatus)
	*p = x
	return p
}

func (x ObjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[2].Descriptor()
}

func (ObjectStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[2]
}

func (x ObjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStatus.Descriptor instead.
func (ObjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

// InventoryStatus - response status for inventory collection
type InventoryStatus int32

const (
	InventoryStatus_INVENTORY_STATUS_UNSPECIFIED InventoryStatus = 0
	InventoryStatus_INVENTORY_STATUS_SUCCESS     InventoryStatus = 1
	InventoryStatus_INVENTORY_STATUS_FAILED      InventoryStatus = 2
)

// Enum value maps for InventoryStatus.
var (
	InventoryStatus_name = map[int32]string{
		0: "INVENTORY_STATUS_UNSPECIFIED",
		1: "INVENTORY_STATUS_SUCCESS",
		2: "INVENTORY_STATUS_FAILED",
	}
	InventoryStatus_value = map[string]int32{
		"INVENTORY_STATUS_UNSPECIFIED": 0,
		"INVENTORY_STATUS_SUCCESS":     1,
		"INVENTORY_STATUS_FAILED":      2,
	}
)

func (x InventoryStatus) Enum() *InventoryStatus {
	p := new(InventoryStatus)
	*p = x
	return p
}

func (x InventoryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[3].Descriptor()
}

func (InventoryStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[3]
}

func (x InventoryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryStatus.Descriptor instead.
func (InventoryStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

// WorkflowOptions - options for executing workflows
// TODO: Fix typo in attribute name
type WorkflowOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RetryCount      *int32                 `protobuf:"varint,1,opt,name=retry_count,json=retryCount,proto3,oneof" json:"retry_count,omitempty"`
	RetryInt32Erval *int32                 `protobuf:"varint,2,opt,name=retry_int32erval,json=retryInt32erval,proto3,oneof" json:"retry_int32erval,omitempty"`
	Policy          *WorkflowPolicy        `protobuf:"varint,3,opt,name=policy,proto3,enum=workflows.v1.WorkflowPolicy,oneof" json:"policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowOptions) Reset() {
	*x = WorkflowOptions{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions) ProtoMessage() {}

func (x *WorkflowOptions) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions.ProtoReflect.Descriptor instead.
func (*WorkflowOptions) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowOptions) GetRetryCount() int32 {
	if x != nil && x.RetryCount != nil {
		return *x.RetryCount
	}
	return 0
}

func (x *WorkflowOptions) GetRetryInt32Erval() int32 {
	if x != nil && x.RetryInt32Erval != nil {
		return *x.RetryInt32Erval
	}
	return 0
}

func (x *WorkflowOptions) GetPolicy() WorkflowPolicy {
	if x != nil && x.Policy != nil {
		return *x.Policy
	}
	return WorkflowPolicy_WORKFLOW_POLICY_UNSPECIFIED
}

// TransactionID - Identity for temporal workflow
type TransactionID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object ID of the resource
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Microsecond timestamp for object serialization
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionID) Reset() {
	*x = TransactionID{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionID) ProtoMessage() {}

func (x *TransactionID) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionID.ProtoReflect.Descriptor instead.
func (*TransactionID) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionID) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TransactionID) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// InventoryPage - pagination information about inventory
type InventoryPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of pages
	TotalPages int32 `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	// Current page number
	CurrentPage int32 `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	// Number of items per page
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Total number of items
	TotalItems int32 `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	// IDs of all items
	ItemIds       []string `protobuf:"bytes,5,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryPage) Reset() {
	*x = InventoryPage{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryPage) ProtoMessage() {}

func (x *InventoryPage) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryPage.ProtoReflect.Descriptor instead.
func (*InventoryPage) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryPage) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *InventoryPage) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *InventoryPage) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *InventoryPage) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *InventoryPage) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\fworkflows.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x0fWorkflowOptions\x12$\n" +
	"\vretry_count\x18\x01 \x01(\x05H\x00R\n" +
	"retryCount\x88\x01\x01\x12.\n" +
	"\x10retry_int32erval\x18\x02 \x01(\x05H\x01R\x0fretryInt32erval\x88\x01\x01\x129\n" +
	"\x06policy\x18\x03 \x01(\x0e2\x1c.workflows.v1.WorkflowPolicyH\x02R\x06policy\x88\x01\x01B\x0e\n" +
	"\f_retry_countB\x13\n" +
	"\x11_retry_int32ervalB\t\n" +
	"\a_policy\"j\n" +
	"\rTransactionID\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xac\x01\n" +
	"\rInventoryPage\x12\x1f\n" +
	"\vtotal_pages\x18\x01 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x05R\n" +
	"totalItems\x12\x19\n" +
	"\bitem_ids\x18\x05 \x03(\tR\aitemIds*\xc7\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_CREATED\x10\x01\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_IN_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_STATUS_REQUEUED\x10\x03\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_SUCCESS\x10\x04\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_FAILURE\x10\x05*z\n" +
	"\x0eWorkflowPolicy\x12\x1f\n" +
	"\x1bWORKFLOW_POLICY_UNSPECIFIED\x10\x00\x12%\n" +
	"!WORKFLOW_POLICY_DELETE_ON_FAILURE\x10\x01\x12 \n" +
	"\x1cWORKFLOW_POLICY_ASYNC_NOTIFY\x10\x02*\xb6\x01\n" +
	"\fObjectStatus\x12\x1d\n" +
	"\x19OBJECT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OBJECT_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19OBJECT_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15OBJECT_STATUS_DELETED\x10\x03\x12\x19\n" +
	"\x15OBJECT_STATUS_UPDATED\x10\x04\x12\x17\n" +
	"\x13OBJECT_STATUS_READY\x10\x05*n\n" +
	"\x0fInventoryStatus\x12 \n" +
	"\x1cINVENTORY_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INVENTORY_STATUS_SUCCESS\x10\x01\x12\x1b\n" +
	"\x17INVENTORY_STATUS_FAILED\x10\x02BCZAgithub.com/NVIDIA/ncx-infra-controller-rest/workflow-schema/protob\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_proto_goTypes = []any{
	(WorkflowStatus)(0),           // 0: workflows.v1.WorkflowStatus
	(WorkflowPolicy)(0),           // 1: workflows.v1.WorkflowPolicy
	(ObjectStatus)(0),             // 2: workflows.v1.ObjectStatus
	(InventoryStatus)(0),          // 3: workflows.v1.InventoryStatus
	(*WorkflowOptions)(nil),       // 4: workflows.v1.WorkflowOptions
	(*TransactionID)(nil),         // 5: workflows.v1.TransactionID
	(*InventoryPage)(nil),         // 6: workflows.v1.InventoryPage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_workflow_proto_depIdxs = []int32{
	1, // 0: workflows.v1.WorkflowOptions.policy:type_name -> workflows.v1.WorkflowPolicy
	7, // 1: workflows.v1.TransactionID.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_workflow_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
